<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login now</name>
   <tag></tag>
   <elementGuidId>8943ec62-ec1a-4c15-8ee4-b4b08fea695d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='prp-link-loginnow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prp-link-loginnow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f3bddf2-640d-4a41-bdfd-b3716099e002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-link-loginnow</value>
      <webElementGuid>4a86a56b-6e75-472f-89c9-2d4442aa955c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dh-link text-15px</value>
      <webElementGuid>607bab6f-ed14-491c-8daf-b5d417905c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login now</value>
      <webElementGuid>55d19e01-b8b4-4a09-ad90-1629cc1f814a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-link-loginnow&quot;)</value>
      <webElementGuid>14420d8f-fae2-4e8f-bc9f-e0177f45813c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='prp-link-loginnow']</value>
      <webElementGuid>765e2551-5fe6-4bed-8e36-2e8362f80a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prp-wrapper-loginnow']/span/a</value>
      <webElementGuid>c24d2d5b-b775-4e06-b508-f5d4ecf6bc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login now')]</value>
      <webElementGuid>a21aa764-d8ea-46ec-89c6-3c6c9649b359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need assistance? Chat with us!'])[1]/preceding::a[1]</value>
      <webElementGuid>d6274bd3-6c7d-4fad-969a-2202de340a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'prp-link-loginnow', '&quot;', ')')])[1]/preceding::a[2]</value>
      <webElementGuid>fc6b663f-2bca-4516-ace0-b13aecbe254b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login now']/parent::*</value>
      <webElementGuid>27694b25-1420-4b1f-9ffc-93bff018700d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>53a8b438-d1fc-448a-aa73-903fe6d86d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'prp-link-loginnow' and (text() = 'Login now' or . = 'Login now')]</value>
      <webElementGuid>65677bec-93f6-4dee-b82d-0fa4290ef4fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
