<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Need assistance Chat with us</name>
   <tag></tag>
   <elementGuidId>22d829e8-a264-406f-8134-76084e642af0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='prp-login-chat-wa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prp-login-chat-wa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>99271831-849c-4343-8e40-217d7ffea256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>898f6572-54db-4361-b554-7699fd7695b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c35e54ce-26af-46ef-a87e-32b91ff93d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-login-chat-wa</value>
      <webElementGuid>2241fd11-d17d-4647-9176-69ad4f7cdef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-wa</value>
      <webElementGuid>67932dc2-6ca9-4ce4-b4f7-f53227cc911d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Need assistance? Chat with us!</value>
      <webElementGuid>c0127dbc-32d6-4b4a-8986-e1d90db3bd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-login-chat-wa&quot;)</value>
      <webElementGuid>31a8834e-b829-4a9a-85ae-aae6ae54aae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='prp-login-chat-wa']</value>
      <webElementGuid>06353686-5abc-472a-8011-604b49ed770b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signUpV2']/div/div[2]/div/div[6]/div[2]/a</value>
      <webElementGuid>d28caa99-2d90-45bd-96b6-0c47da348e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login now'])[1]/following::a[1]</value>
      <webElementGuid>3abd5761-4969-4d23-a53c-c5f5d6297f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'prp-login-chat-wa', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>8b2127b5-416c-4108-9336-c2cca83f8258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>84b81122-ed20-4f95-8884-9baad2be01c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>71bc0e19-ce3c-4e48-9e07-2900a962cc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'prp-login-chat-wa' and (text() = '  Need assistance? Chat with us!' or . = '  Need assistance? Chat with us!')]</value>
      <webElementGuid>18a6d94b-30ce-4670-a5c9-afde0ca032ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
