<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Resend the OTP to my mobile phone</name>
   <tag></tag>
   <elementGuidId>6a029bd4-2b59-4ffe-b216-eb371300a246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify'])[1]/preceding::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#resendOTP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3be0e246-f498-46ff-b264-0cc740567ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resendOTP</value>
      <webElementGuid>f596be33-698c-4014-991a-fb25bc1a287d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link dh-link text-center text-15px</value>
      <webElementGuid>d119531f-752e-4593-9ad5-aa6572ed868e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resend the OTP to my mobile phone
                                </value>
      <webElementGuid>775fe718-a3de-4b05-aa8b-35c987924d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resendOTP&quot;)</value>
      <webElementGuid>9ea4ffe4-babc-4d69-b3d4-d429b27eda2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='resendOTP']</value>
      <webElementGuid>6df6b85e-ac1b-4fb0-a51e-f11022601913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-otp']/div[2]/a</value>
      <webElementGuid>f7f1bf01-967d-48f9-b89b-e15497fab5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Resend the OTP to my mobile phone')]</value>
      <webElementGuid>2cc6c693-2345-42e0-83e9-20f48b7e5749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A one-time PIN has been sent via SMS to your mobile number'])[1]/following::a[1]</value>
      <webElementGuid>98b48c51-8b5d-4b93-bd2a-4b835e2247e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your OTP'])[1]/following::a[1]</value>
      <webElementGuid>f4fc17f5-607a-4234-b3b8-860379c483a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify'])[1]/preceding::a[1]</value>
      <webElementGuid>aa9c47fd-daa9-48b1-8b80-c75b4c7bab11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'resendOTP', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>bcf461d5-8861-4007-a565-31781857828e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resend the OTP to my mobile phone']/parent::*</value>
      <webElementGuid>a7ceb62f-2173-4a79-ac94-e96d4414be89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>f54fc6df-0fdd-47ed-bf0a-8906d6895ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'resendOTP' and (text() = 'Resend the OTP to my mobile phone
                                ' or . = 'Resend the OTP to my mobile phone
                                ')]</value>
      <webElementGuid>8a85e259-90fc-4cd3-b4d4-255d5972c25a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
