<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign Up with an Email</name>
   <tag></tag>
   <elementGuidId>710caa9b-28b7-4165-8d58-308e3c4d36e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prp-link-signup-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='prp-link-signup-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f5daed49-bb1a-47aa-9946-75dbf35ebf3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>fb5d8aa4-0e3d-419e-b29c-18f192956bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-link-signup-email</value>
      <webElementGuid>114d55a6-f1e0-4171-946a-0e0b34f9b895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white text-16px text-decoration-none</value>
      <webElementGuid>bb8b6a30-a9dc-496f-a720-6cbd2e92b59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up with an Email
                        </value>
      <webElementGuid>0bf5b57e-1339-4164-b46f-85213002448f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-link-signup-email&quot;)</value>
      <webElementGuid>91b73618-a724-4161-9ee0-d085215f0083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='prp-link-signup-email']</value>
      <webElementGuid>487c6c84-6dc6-4314-b6c0-febeff05b87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='prp-btn-signup-email']/a</value>
      <webElementGuid>17edcddc-3cde-48bc-864d-34807443d5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign Up with an Email')]</value>
      <webElementGuid>699d144f-a758-4794-9f10-12e06faee751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Healthcare is a journey. Start here.'])[1]/following::a[1]</value>
      <webElementGuid>6e9671bc-7d1e-4d7b-97f5-3fb3fcd8012f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an account'])[1]/following::a[1]</value>
      <webElementGuid>81b8dac9-e395-43b8-bccd-e3d523baf8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up with'])[1]/preceding::a[1]</value>
      <webElementGuid>fb0af826-a3a4-4afb-97db-fa60a7269251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign Up with an Email']/parent::*</value>
      <webElementGuid>f024bee6-abb5-4218-801c-d657b28d861e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>0baa9c13-9252-4fa7-a0cb-f120b5c8f479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/a</value>
      <webElementGuid>9433ef6f-f7f6-4684-96ab-bb1a56263270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'prp-link-signup-email' and (text() = 'Sign Up with an Email
                        ' or . = 'Sign Up with an Email
                        ')]</value>
      <webElementGuid>6e3455f2-ecdd-413c-9968-705a21049979</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
