<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nationality_selected-flag</name>
   <tag></tag>
   <elementGuidId>8a92047c-3d74-4d20-8adb-b8d68204420e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.group.group-nationality > div.input-group.form-group > div.country-select.inside > div.flag-dropdown > div.selected-flag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='personal_info_part']/form/div[6]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e8b767e2-6111-4389-b791-2a889d0d9898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected-flag</value>
      <webElementGuid>3556a633-3dfc-4692-9e60-6593bd331dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Singaporean</value>
      <webElementGuid>44aaceb5-98ea-4e60-bc8f-1ca3be5196e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group group-nationality&quot;]/div[@class=&quot;input-group form-group&quot;]/div[@class=&quot;country-select inside&quot;]/div[@class=&quot;flag-dropdown&quot;]/div[@class=&quot;selected-flag&quot;]</value>
      <webElementGuid>fce8b855-639b-4af1-8208-5758dc2f9c24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal_info_part']/form/div[6]/div/div/div/div</value>
      <webElementGuid>068e47ce-6c1c-4f50-be94-1dee1acfa5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality'])[1]/following::div[4]</value>
      <webElementGuid>7a124b95-f919-4129-ac8d-3b8ac74f220c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zimbabwe'])[1]/following::div[5]</value>
      <webElementGuid>44658619-dae8-4027-9dc7-9b1f59db7665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singaporean'])[1]/preceding::div[4]</value>
      <webElementGuid>9c8723b1-dba3-4a3c-b8d9-5b0e8de6f567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesian'])[1]/preceding::div[5]</value>
      <webElementGuid>8c21d027-5acd-4ee5-9ee4-9248b61b3572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div</value>
      <webElementGuid>af5033d6-a45e-4a9c-877e-01bddc9d32f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Singaporean']</value>
      <webElementGuid>769abb76-5cf4-4c05-85c3-6c711495dfb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
