<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Male</name>
   <tag></tag>
   <elementGuidId>c87d649f-5a18-492d-a728-fc638496e1d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.box-disabled.border-primary.fw-mh.d-flex.flex-column.justify-content-center.align-items-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='personal_info_part']/form/div[3]/div/label/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2778c09-ffe6-424f-a5af-3d473a1466c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>1a83b253-9973-4d1f-a970-f2bf6592ed0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>53d4eb99-9d94-4103-8db2-8ad5d5b12792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>992d739a-4737-459f-b995-2f8fee67b04b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal_info_part']/form/div[3]/div/label/div/div</value>
      <webElementGuid>cd12e371-bed0-4576-b127-86831c321992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::div[3]</value>
      <webElementGuid>66e24f76-5442-479a-b6c0-10e24e588863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::div[4]</value>
      <webElementGuid>fdee1758-80da-49c5-9b77-2197502faa88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/preceding::div[1]</value>
      <webElementGuid>bcc31cd7-12e4-434f-b5f2-2387f7dd3af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div</value>
      <webElementGuid>639fd64d-0605-49b8-92c5-ee38fae0d24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Male' or . = 'Male')]</value>
      <webElementGuid>3e949a7f-5a6c-45d8-af63-f529271f5851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
