<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Country of Residence_flag sg</name>
   <tag></tag>
   <elementGuidId>dad753d9-75fe-4a52-aed7-edcd2cfb4429</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flag.sg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='personal_info_part']/form/div[5]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97660992-00f4-4a35-aa1e-0ffcbf3ae2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flag sg</value>
      <webElementGuid>5e7d2229-d263-40ad-a086-25c2926be026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group group-country&quot;]/div[@class=&quot;input-group form-group&quot;]/div[@class=&quot;country-select inside&quot;]/div[@class=&quot;flag-dropdown&quot;]/div[@class=&quot;selected-flag&quot;]/div[@class=&quot;flag sg&quot;]</value>
      <webElementGuid>50d61c7d-1d46-4dad-8a91-5c32a479a317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal_info_part']/form/div[5]/div/div/div/div/div</value>
      <webElementGuid>ab6f4d97-8fcf-4263-b3f0-839792222336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div</value>
      <webElementGuid>b87bcd15-869c-4ece-b1e7-f40c3e08d52f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
