<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Call me again in  1</name>
   <tag></tag>
   <elementGuidId>a6fbdaae-3804-49ca-a1af-c63e41990bf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='countdownID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#countdownID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e31a8c78-73c2-4a75-9509-8c2fdb6b98da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>countdownID</value>
      <webElementGuid>c05678c8-d861-4043-a184-e26486049dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-15px text-secondary-dark-grey text-center mt-3</value>
      <webElementGuid>d42a06ef-af95-417f-ac58-1a141f8da61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Call me again in : 1.
                            </value>
      <webElementGuid>0b6efde8-3cae-4a61-a3f7-bf753d792538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countdownID&quot;)</value>
      <webElementGuid>643ddc0b-9c7f-40a8-8fe8-712d1a264de3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='countdownID']</value>
      <webElementGuid>2f5af71d-0aaa-44db-ace1-0bf0dbea2464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='verification-part']/div[3]/div</value>
      <webElementGuid>9c73a402-1136-42de-bb9f-effac945715c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can choose to receive your OTP by a voice call by tapping below.'])[1]/following::div[2]</value>
      <webElementGuid>b561ac63-3b5c-4101-a567-6accf7e01ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify'])[1]/preceding::div[5]</value>
      <webElementGuid>452b4b16-bd59-4926-9b47-255cc9b8d392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'countdownID', '&quot;', ')')])[1]/preceding::div[12]</value>
      <webElementGuid>5791965a-ae26-4c24-80fa-0fe20b51d3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Call me again in : 1.']/parent::*</value>
      <webElementGuid>e012062b-516d-4f06-8d14-1d76ac2cdd03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div</value>
      <webElementGuid>db4575fb-bff1-45aa-a5b3-c85fb248ff64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'countdownID' and (text() = '
                                Call me again in : 1.
                            ' or . = '
                                Call me again in : 1.
                            ')]</value>
      <webElementGuid>a391ba9d-b1a0-4808-8246-982e9dc654f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
