<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password</name>
   <tag></tag>
   <elementGuidId>3ee888b3-e464-4a21-b355-0a280046e70e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='account_info_part']/form/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group.position-relative</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d9aa189d-b16c-4177-862e-88c595ce5ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group position-relative</value>
      <webElementGuid>3e2cf16f-da9e-4573-b6ca-c9ccfca9983c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password  </value>
      <webElementGuid>2b9a2c49-b804-4c1d-9f89-fe7e07b4044c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;form-group position-relative&quot;]</value>
      <webElementGuid>a7a788d1-2f7a-4efa-9898-5b4e443f0abd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account_info_part']/form/div[2]/div</value>
      <webElementGuid>c6f30a11-431c-4d08-935a-4aeecd63f4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[2]</value>
      <webElementGuid>4f76231d-584c-4989-a195-be1c3cc546c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create My Profile'])[1]/following::div[4]</value>
      <webElementGuid>1a8d497f-c4df-4c90-ab7d-7a3a22b4acbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accept and Continue'])[1]/preceding::div[3]</value>
      <webElementGuid>9775fbee-abfb-4d36-837b-3493609846b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div</value>
      <webElementGuid>65d872d0-ebc3-4ebb-bf2d-f6fc6f171588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Password  ' or . = 'Password  ')]</value>
      <webElementGuid>a4ca88c7-b341-4f4a-a3fd-2961b67f9c43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
