<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you_circle text-center</name>
   <tag></tag>
   <elementGuidId>1a0a934b-bc0b-4b49-ab82-901601ad8f56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cover-spin']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.circle.text-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2c557f8-965e-48f4-aa05-1f713ca2a275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>circle text-center</value>
      <webElementGuid>bb98d325-910f-47e6-bc89-3e66eb16f780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cover-spin&quot;)/div[@class=&quot;circle text-center&quot;]</value>
      <webElementGuid>55e27dcb-9a3e-4f70-8423-412cfbc8821e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cover-spin']/div</value>
      <webElementGuid>2d1f4541-2d9a-407c-8581-223ec5092f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success!'])[1]/preceding::div[2]</value>
      <webElementGuid>f0f69126-ea61-4a19-b921-9c3c95cfd3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div</value>
      <webElementGuid>129ce919-dc1c-4560-bf79-1c4a0b34eba4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
