<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon-success-otp-page</name>
   <tag></tag>
   <elementGuidId>d31dbf0e-8e2d-4090-bfa9-30c6c4efda20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='prp-img-icon-success']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prp-img-icon-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>700bd22e-2e78-4b75-b700-e7dee2a5755f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-img-icon-success</value>
      <webElementGuid>7eb9d1d9-9e5f-45fd-935e-665863c3558f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/success.svg</value>
      <webElementGuid>cee91e28-5d32-4371-b110-ea0550b36e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ec9847dd-e867-492b-9d96-b2c6c14822a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto</value>
      <webElementGuid>68f05934-8edc-4977-9221-2827e08114eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-img-icon-success&quot;)</value>
      <webElementGuid>021308f4-d0f4-4e86-9780-e1ffa85791b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='prp-img-icon-success']</value>
      <webElementGuid>0674b033-aadf-491e-85a6-d9edc1595d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-success']/div/div/div[2]/img</value>
      <webElementGuid>19703a03-4001-4423-b600-3f64fc61023f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>077393b0-d5f6-47db-969e-281af3f68a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'prp-img-icon-success' and @src = 'assets/images/success.svg']</value>
      <webElementGuid>db8a53cc-62d0-423e-93e6-d09553220403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
