<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_boats_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>3078952f-934a-4656-94d4-19cfa8fb8e76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4210103d-c6b8-4b01-98db-235829716fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>a82d0205-bc6a-49bd-8c1e-3d7729d0290c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AIIukzjudKMZ53XQz28nfQaCsH88oBXm5KkvfraYqe83AUgX-v04e1rljI1ski2fqTWpqJ3Fbk8fXtkEfWyMiJbl55oiQ8MMdpI0dYKLkj7HLik-21FURb7bysEKiRsc09OKuhBUfb-P3rhJtEjRjacT7VvThayjGZXN6E_r6lFCJ1HlF-Im0YapblkEhxyJE5WPWnZshhkzkX2qeFIyTEz0OdCuoJbttA&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA</value>
      <webElementGuid>6e6d145d-5ce4-4928-bfab-62b8a6424c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>e05f4b79-d644-4383-a0b0-e8f6ebe0bd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Patient Registration/iframe_Apply_c-dlmqort5sbyw</value>
      <webElementGuid>8a2682b7-343f-4f5b-8995-1b75f3a784d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>dc5debd5-8c49-489c-aa1d-a6b6f8b45df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AIIukzjudKMZ53XQz28nfQaCsH88oBXm5KkvfraYqe83AUgX-v04e1rljI1ski2fqTWpqJ3Fbk8fXtkEfWyMiJbl55oiQ8MMdpI0dYKLkj7HLik-21FURb7bysEKiRsc09OKuhBUfb-P3rhJtEjRjacT7VvThayjGZXN6E_r6lFCJ1HlF-Im0YapblkEhxyJE5WPWnZshhkzkX2qeFIyTEz0OdCuoJbttA&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA')])[5]</value>
      <webElementGuid>e379b4e0-0eab-401c-b8e2-76642d50e83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>e8c0ac21-90b4-48a9-8c1d-801d1649abba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AIIukzjudKMZ53XQz28nfQaCsH88oBXm5KkvfraYqe83AUgX-v04e1rljI1ski2fqTWpqJ3Fbk8fXtkEfWyMiJbl55oiQ8MMdpI0dYKLkj7HLik-21FURb7bysEKiRsc09OKuhBUfb-P3rhJtEjRjacT7VvThayjGZXN6E_r6lFCJ1HlF-Im0YapblkEhxyJE5WPWnZshhkzkX2qeFIyTEz0OdCuoJbttA&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA']</value>
      <webElementGuid>3c2b22c8-a3ce-425a-9872-a305188ce7a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
