<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Error occured_logo-mh360</name>
   <tag></tag>
   <elementGuidId>5519410a-60ff-40b0-a272-604cb0624443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='logo-mh360']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logo-mh360</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aba7d6dd-4882-4d6d-b25c-fac969b8fec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logo-mh360</value>
      <webElementGuid>d359ece2-e810-472d-a274-695f2bb52b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/logo-mh360.png</value>
      <webElementGuid>11f7159b-c5bb-4e6c-8b6e-7771889d6b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-mh360</value>
      <webElementGuid>122d440a-ce92-4482-b35f-0eda09dda3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-mh360&quot;)</value>
      <webElementGuid>b1c24f13-f119-43a0-b847-c2e8fce33cd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='logo-mh360']</value>
      <webElementGuid>d912ff57-e82d-4e74-96b8-9f8fe5cc9911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register']/div[3]/div/div/span/img</value>
      <webElementGuid>07f9d463-4d47-42b3-b3b0-e62cbe2f3cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>b57f5e97-fb76-4c09-b189-d4959c95338b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'logo-mh360' and @src = 'assets/images/logo-mh360.png']</value>
      <webElementGuid>6547dee4-9791-4a27-bdc9-66abf878a799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
