<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Thank you_prp-img-loader</name>
   <tag></tag>
   <elementGuidId>a2c4c58f-29d5-4211-82e7-8ffb6da962e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='prp-img-loader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prp-img-loader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>904537e4-21a9-4885-acb2-b8b359aceb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-img-loader</value>
      <webElementGuid>4c80a340-fb26-4926-96f4-ffd40d08d538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/loader.gif</value>
      <webElementGuid>eb954c2b-89ef-4b1f-8d01-7a745c299527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-img-loader&quot;)</value>
      <webElementGuid>8139cc80-5747-4d40-8164-5331e2ae3638</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='prp-img-loader']</value>
      <webElementGuid>99c88150-beb6-4cda-95a3-41f9ae32e1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cover-spin']/div/img</value>
      <webElementGuid>ccd61c58-3130-4e09-aba5-d8c134cd6966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5fe7c680-d780-4626-b4cd-45a5f08910e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'prp-img-loader' and @src = 'assets/images/loader.gif']</value>
      <webElementGuid>30506426-03fa-4838-a204-98a7c2300b42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
