<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Create an account_prp-img-title</name>
   <tag></tag>
   <elementGuidId>c0ea342f-7414-4e3a-bee9-bf8bd2e45164</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='prp-img-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prp-img-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>40710e2a-5637-4dac-abd1-104c0b880cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/logo-mh360.png</value>
      <webElementGuid>37a82b56-a680-40dc-91cf-51222f79376d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-img-title</value>
      <webElementGuid>4a61211a-a263-44df-a148-653919d5eb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-mh360</value>
      <webElementGuid>6d594736-eea8-48ed-8fb5-31180e2a2dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-img-title&quot;)</value>
      <webElementGuid>052ba9ed-510f-4083-8c0c-8042dc85a855</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='prp-img-title']</value>
      <webElementGuid>8b30b7eb-706f-44c9-a95c-34ee286e5758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signUpV2']/div/div/span/img</value>
      <webElementGuid>6624db84-b54f-4fb1-b90a-f1a5564d196b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>81b1c5a7-2327-412f-a61a-8c152825ce69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/logo-mh360.png' and @id = 'prp-img-title']</value>
      <webElementGuid>4bc1a3a5-a46d-4d96-8b00-0b88f2bcc439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
