<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Thank you_prp-img-icon-success</name>
   <tag></tag>
   <elementGuidId>126e8d12-7df8-4aeb-abd7-47a85b7aa1f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prp-img-icon-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='prp-img-icon-success']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>39dfee08-e87f-479b-9260-e686408e09eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-img-icon-success</value>
      <webElementGuid>5f648a59-f1f1-4273-b29d-aec92725e4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/success.svg</value>
      <webElementGuid>c0207e40-8f63-4dfc-8f6d-9851cdcfd69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5792e3a5-6ef6-4a0a-9d70-789e53881967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto</value>
      <webElementGuid>8e489f8a-44eb-43c8-98e9-1fa9e5b8adc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-img-icon-success&quot;)</value>
      <webElementGuid>f4664501-ffb1-4a52-80c1-889b770abf1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='prp-img-icon-success']</value>
      <webElementGuid>b3fc4d69-40ce-4408-a5cb-b09579159e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-success']/div/div/div[2]/img</value>
      <webElementGuid>82602556-6e89-4334-8ea0-9d3c3aea7a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>aa8f443f-5a45-4535-8410-bf26ad7a0b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'prp-img-icon-success' and @src = 'assets/images/success.svg']</value>
      <webElementGuid>d43adb70-bd51-49e5-9685-93018c3d37e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
