<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_motorcycles_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>a79765be-a306-43d4-8f16-e597ba1b8d73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>89255f0a-02ed-452c-8df7-7b26cdc312b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>aac3b887-3d70-4625-892d-4c27dac7f83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AIIukzi7WYcDge9IJtMRvER_JzdBhPgXOUulFPzXmbzKjb8LfeSpCHwrbk73Sw3djFczgYMqHTT1UTEhdvtHCc_eTedv8mWN8fvkNlQvyA6RKkCvKNEIXS8JF1z_xsoopjinpi8NLyJkYkPs79FPmA_IKFN3NSRBmd1TM0s9t3jfp9wI5_jluMStXOvRvfG3wCTufrfi80C5lkbfVkpp3_4Sc-xYy3mz2Q&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA</value>
      <webElementGuid>c95e6943-1b94-4682-833f-5998e3ac4afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>900352e2-1d0a-41ea-a98a-a778e67a1de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Patient Registration/iframe_Apply_c-26l3jortjzd1</value>
      <webElementGuid>000113fb-51af-4f16-a64f-27266fb179fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      <webElementGuid>41f580f0-2448-4798-984e-ddc65bae68a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AIIukzi7WYcDge9IJtMRvER_JzdBhPgXOUulFPzXmbzKjb8LfeSpCHwrbk73Sw3djFczgYMqHTT1UTEhdvtHCc_eTedv8mWN8fvkNlQvyA6RKkCvKNEIXS8JF1z_xsoopjinpi8NLyJkYkPs79FPmA_IKFN3NSRBmd1TM0s9t3jfp9wI5_jluMStXOvRvfG3wCTufrfi80C5lkbfVkpp3_4Sc-xYy3mz2Q&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA')])[2]</value>
      <webElementGuid>d98bacb7-478b-4ed4-99b8-3a06ec745508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>e0d13ab6-a57b-4d0a-8b09-9ac8c48f3de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AIIukzi7WYcDge9IJtMRvER_JzdBhPgXOUulFPzXmbzKjb8LfeSpCHwrbk73Sw3djFczgYMqHTT1UTEhdvtHCc_eTedv8mWN8fvkNlQvyA6RKkCvKNEIXS8JF1z_xsoopjinpi8NLyJkYkPs79FPmA_IKFN3NSRBmd1TM0s9t3jfp9wI5_jluMStXOvRvfG3wCTufrfi80C5lkbfVkpp3_4Sc-xYy3mz2Q&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA']</value>
      <webElementGuid>52d6f985-8901-4095-a81e-eeeb8b240dbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
