<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Allow_prp-img-title</name>
   <tag></tag>
   <elementGuidId>bebea330-c41b-48d6-88e4-2068ddf4a529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='prp-img-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prp-img-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f4d1443e-7de8-4eb2-9d45-fc5baa29f697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/logo-mh360.png</value>
      <webElementGuid>ab7a041f-e8c1-4da5-ae08-633df3e9a2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-img-title</value>
      <webElementGuid>cfc4865e-7333-41ce-bdc9-b1a5a92fb2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-mh360</value>
      <webElementGuid>05d988cd-70d8-4792-94f0-0091f3a10b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-img-title&quot;)</value>
      <webElementGuid>357c5a03-4441-4b2a-98ab-d5b1a1d924e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='prp-img-title']</value>
      <webElementGuid>04bd1a69-85a2-4d2c-ae21-a5466cb511f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signUpV2']/div/div/span/img</value>
      <webElementGuid>b42eb3fc-0cba-40f5-a0e7-6ff0ded59ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/img</value>
      <webElementGuid>bf1325f4-37ee-47c6-878a-b9a14c85b837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/logo-mh360.png' and @id = 'prp-img-title']</value>
      <webElementGuid>c66d1f6a-3b24-46af-ba36-cbe95e857ec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
