<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimum 8 characters_flexCheckChecked</name>
   <tag></tag>
   <elementGuidId>1012808a-bdca-4727-9ef6-6bab24fcc8fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flexCheckChecked</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flexCheckChecked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b008ebd-df83-4c16-be46-1ee9478d6b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>085fc3a1-669b-4937-98e7-828740a81314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexCheckChecked</value>
      <webElementGuid>aaafd896-86b1-4411-a7be-4bfeb55dd878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e66de617-dab6-4a05-8e9e-aafb02980eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flexCheckChecked&quot;)</value>
      <webElementGuid>9ea39da5-8124-4baa-932d-eeeec1a57484</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flexCheckChecked']</value>
      <webElementGuid>c40b661b-6298-4054-b0e8-d092cc8083bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account_info_part']/form/div[4]/input</value>
      <webElementGuid>4fe42014-5c76-43e9-9b02-af97db145319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>1af7e419-93df-43da-94de-390a081952b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'flexCheckChecked']</value>
      <webElementGuid>8b6cf47f-dfe7-42f5-88ec-6668fbca2991</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
