<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_A one-time PIN has been sent via SMS _fd653b</name>
   <tag></tag>
   <elementGuidId>3e48880a-c717-4d0d-8740-1b0556c95913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otp0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03292dd4-50f4-4be1-b8ba-5f562b871755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp0</value>
      <webElementGuid>286a26b2-7cc5-4fc7-9b93-969d1b346773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>093fd71e-6751-4f7c-9ed3-dfa35bd23745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>bf21ba24-1720-4854-9f49-f67982c971e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>54e53f69-498a-4e98-b289-031c51d57811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>digit-group-single fw-600</value>
      <webElementGuid>ba66b86d-1317-45b9-a5f0-f95b66b3508b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp0&quot;)</value>
      <webElementGuid>20bba21a-68e8-41d8-8b9b-f3d819cafb22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp0']</value>
      <webElementGuid>d195ee51-965b-48d9-9c53-65e81cdfeacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OTPInput']/input</value>
      <webElementGuid>b31ef324-a31a-4d1d-bad6-e1ba3b14a5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c995959f-ac97-47bd-b8a4-d1cd0cdec453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp0' and @type = 'tel']</value>
      <webElementGuid>7f53ae99-7710-4c6f-b87a-c2b500a70d2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
