<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wrong ID may result in missing result_ed1f2d</name>
   <tag></tag>
   <elementGuidId>6afdfa9b-76ee-42f1-a9fe-d4cf21dd8c70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d182b254-d035-4d0e-8c5b-8fb732e3e650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c78c34b3-2925-4176-a5b8-1a24495ee782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.g.S1234567D</value>
      <webElementGuid>42a62f0b-c4a7-45c9-8972-e47688232de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>idNumber</value>
      <webElementGuid>3795e2b3-b830-4137-947e-5dc32f539344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idNumber</value>
      <webElementGuid>43674705-862d-410d-8828-60da9f36c50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>54a4b744-c22b-4f5e-8acb-ca7e24f9fe38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idNumber&quot;)</value>
      <webElementGuid>5b02343a-7c83-43be-b0f3-e8df4435acb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idNumber']</value>
      <webElementGuid>26914e13-1c66-4172-9350-73d95682805b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal_info_part']/form/div[7]/div/div/div[2]/input</value>
      <webElementGuid>ca3d0b44-23e7-4faa-8573-a4dc8c20edd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ecd21463-9a9c-4837-8e5f-555f454ced84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'E.g.S1234567D' and @name = 'idNumber' and @id = 'idNumber']</value>
      <webElementGuid>3804c8d4-38f5-4826-a47f-371b3ad6f9f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
