<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimum 8 characters_flexCheckChecked2</name>
   <tag></tag>
   <elementGuidId>9452c38e-8303-48eb-b35a-bc8e361fb1f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flexCheckChecked2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flexCheckChecked2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb4b8eac-3ee1-42b0-8ea8-9b3c641e3d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f5549737-1ff7-4f98-928a-757c165bde81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexCheckChecked2</value>
      <webElementGuid>e79c2f90-4488-4364-880f-bdc8021ae2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a083c9d1-d412-4bf5-8c6a-dcf221b6220d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flexCheckChecked2&quot;)</value>
      <webElementGuid>4aebf49b-dea7-4aec-8f38-60e718da38d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flexCheckChecked2']</value>
      <webElementGuid>a48dea2e-cded-4ef6-8c46-77de9f7343dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account_info_part']/form/div[5]/input</value>
      <webElementGuid>353b37a6-1d4d-49a6-9eb8-cb6453c7b002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>884a11ef-fac4-491d-aebb-a6bf969248b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'flexCheckChecked2']</value>
      <webElementGuid>27f6fbd2-d7b3-412f-93b6-ffbadfb8dd79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
