<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Indonesia62</name>
   <tag></tag>
   <elementGuidId>78043ac9-9893-4627-98e7-ac94b5050d3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iti-1__item-id-preferred</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='iti-1__item-id-preferred']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a4df8b26-7341-411a-898b-872176bf7a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country iti__preferred iti__highlight</value>
      <webElementGuid>846f4464-4d80-4a54-b5da-202d19a225c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>52a70488-5e19-4670-b617-415f2955e241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iti-1__item-id-preferred</value>
      <webElementGuid>66529cd4-bdad-44f8-9d53-bd656ce533d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f7c0f56e-1936-4f05-b7f1-83498a09ab1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>9cbc378f-dea2-4a75-8a42-36274acf67f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>57402179-2735-4794-ba92-37f0dd65b34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia+62</value>
      <webElementGuid>7ab247ae-b47a-4dcf-8006-71f81c846065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-1__item-id-preferred&quot;)</value>
      <webElementGuid>5e543113-c835-4d1a-bd0f-73fbc8fce3fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='iti-1__item-id-preferred']</value>
      <webElementGuid>1932ec08-92ea-437a-9236-9dd77c22a070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='iti-1__country-listbox']/li[2]</value>
      <webElementGuid>355f8d94-e33c-436f-af2b-fa7251ba49f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore'])[3]/following::li[1]</value>
      <webElementGuid>cc51cb6b-3efe-46f6-b9c8-5ef1481357d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::li[2]</value>
      <webElementGuid>a44a6737-3b89-40a9-a643-72ec41cf451a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia'])[3]/preceding::li[1]</value>
      <webElementGuid>f92c93e1-fc09-460b-a1dd-77b2151354fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/ul/li[2]</value>
      <webElementGuid>6f73f5fb-fb43-42be-9f35-5cd84bbe08e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'iti-1__item-id-preferred' and (text() = 'Indonesia+62' or . = 'Indonesia+62')]</value>
      <webElementGuid>cce3ce09-cad8-4f2f-84f0-b983e13ee05d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
