<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo-mh360-otp-page</name>
   <tag></tag>
   <elementGuidId>0de93e02-bb8c-44e0-9da8-4532b33773fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='logo-mh360']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logo-mh360</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f75fd1d3-8915-4f28-b324-e9dbe2b408df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logo-mh360</value>
      <webElementGuid>4110e946-d6f7-4fd3-a3ff-c953a94abb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/logo-mh360.png</value>
      <webElementGuid>6288a948-8b9e-4dfa-8b9c-5d9909ce125d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-mh360</value>
      <webElementGuid>b2c603ee-df4f-48a3-a775-4a88432b6825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-mh360&quot;)</value>
      <webElementGuid>942bad28-577e-47d0-8bb7-ee2ca5bb4e4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='logo-mh360']</value>
      <webElementGuid>864dcfde-5f85-4469-a1ab-e94d79bb4940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register']/div[3]/div/div/span/img</value>
      <webElementGuid>28f6666c-e799-4af3-80f2-c2931399feea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/img</value>
      <webElementGuid>672648bc-9e87-4064-bf7d-57e4a4b4d75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'logo-mh360' and @src = 'assets/images/logo-mh360.png']</value>
      <webElementGuid>91a779e6-6914-4631-9474-9d8d6360497c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
