<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>manual_span_Singaporean</name>
   <tag></tag>
   <elementGuidId>707e776d-52f6-483e-8bce-3b1b005b75f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.group.group-nationality > div.input-group.form-group > div.country-select.inside > div.flag-dropdown > ul.country-list > li.country.preferred.active.highlight > span.country-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9918dc7-6cbe-472e-b123-ec024022780c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-name</value>
      <webElementGuid>fde6d146-9e8d-4d56-9932-70c668cbe23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singaporean</value>
      <webElementGuid>91af4e38-384f-4f31-8eb1-bf4dc93b1dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group group-nationality&quot;]/div[@class=&quot;input-group form-group&quot;]/div[@class=&quot;country-select inside&quot;]/div[@class=&quot;flag-dropdown&quot;]/ul[@class=&quot;country-list&quot;]/li[@class=&quot;country preferred active highlight&quot;]/span[@class=&quot;country-name&quot;]</value>
      <webElementGuid>2436be0e-c967-4408-a1ae-6af8d6734622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78ffa9f7-c4b9-4f35-967e-873fc781a46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-name</value>
      <webElementGuid>e9a7e1de-88bb-49f5-a171-8c5a21a75a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singaporean</value>
      <webElementGuid>e64da406-31e0-4f13-ba0a-1a136cdd4ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group group-nationality&quot;]/div[@class=&quot;input-group form-group&quot;]/div[@class=&quot;country-select inside&quot;]/div[@class=&quot;flag-dropdown&quot;]/ul[@class=&quot;country-list&quot;]/li[@class=&quot;country preferred active highlight&quot;]/span[@class=&quot;country-name&quot;]</value>
      <webElementGuid>0885ce3b-2c34-4ab4-a7bc-45953f1b251a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>aef198a6-2cb1-48ef-a7c6-5bf12cfd732b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-name</value>
      <webElementGuid>c1f0ef4d-b1ba-43f4-923f-2c8c6fc93d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singaporean</value>
      <webElementGuid>26d854c2-619f-4f05-a585-adb98d57e5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group group-nationality&quot;]/div[@class=&quot;input-group form-group&quot;]/div[@class=&quot;country-select inside&quot;]/div[@class=&quot;flag-dropdown&quot;]/ul[@class=&quot;country-list&quot;]/li[@class=&quot;country preferred active highlight&quot;]/span[@class=&quot;country-name&quot;]</value>
      <webElementGuid>25151527-f986-48e5-aa59-158ec5939047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>98cd68db-58c8-480a-a3a5-a91fd8a2c448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-name</value>
      <webElementGuid>251e2395-5ffd-441e-a0f3-2316744c6dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singaporean</value>
      <webElementGuid>530fa06d-43aa-4093-bdfd-d5fd9ff94f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group group-nationality&quot;]/div[@class=&quot;input-group form-group&quot;]/div[@class=&quot;country-select inside&quot;]/div[@class=&quot;flag-dropdown&quot;]/ul[@class=&quot;country-list&quot;]/li[@class=&quot;country preferred active highlight&quot;]/span[@class=&quot;country-name&quot;]</value>
      <webElementGuid>76209123-471d-48f8-a0b1-6e0dbef2ad08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ce27f169-df44-4cba-be0d-8ba828243a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-name</value>
      <webElementGuid>65089b24-a3e5-4c40-816a-5434aede1581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singaporean</value>
      <webElementGuid>fa838b34-9186-4d87-983b-3b472760223f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group group-nationality&quot;]/div[@class=&quot;input-group form-group&quot;]/div[@class=&quot;country-select inside&quot;]/div[@class=&quot;flag-dropdown&quot;]/ul[@class=&quot;country-list&quot;]/li[@class=&quot;country preferred active highlight&quot;]/span[@class=&quot;country-name&quot;]</value>
      <webElementGuid>f1c9d54d-20f7-47df-bf69-a55ba8bea251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>325e16c0-3ad3-453d-8680-2662a8019459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-name</value>
      <webElementGuid>feb570c5-cac6-4a46-8669-57075fa22ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singaporean</value>
      <webElementGuid>d168579f-098f-45b2-8c3a-5f0e59838516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group group-nationality&quot;]/div[@class=&quot;input-group form-group&quot;]/div[@class=&quot;country-select inside&quot;]/div[@class=&quot;flag-dropdown&quot;]/ul[@class=&quot;country-list&quot;]/li[@class=&quot;country preferred active highlight&quot;]/span[@class=&quot;country-name&quot;]</value>
      <webElementGuid>6b198536-b081-4c6d-9bc9-9a7a42ceb57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d7a56ab9-31df-434e-9b10-ea17a8f84bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-name</value>
      <webElementGuid>0c6b4141-7de5-4f23-ac34-dd24f5c63c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singaporean</value>
      <webElementGuid>d0e964f4-fd90-44fc-ab5d-68b3048febb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group group-nationality&quot;]/div[@class=&quot;input-group form-group&quot;]/div[@class=&quot;country-select inside&quot;]/div[@class=&quot;flag-dropdown&quot;]/ul[@class=&quot;country-list&quot;]/li[@class=&quot;country preferred active highlight&quot;]/span[@class=&quot;country-name&quot;]</value>
      <webElementGuid>86347ad1-8ce4-4389-a9ec-c5ccecc41430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>618295e7-406d-4152-b150-889b89a9b5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-name</value>
      <webElementGuid>d79a1b47-0fae-4ace-b471-f30016ecf991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singaporean</value>
      <webElementGuid>5aadab06-bf80-411c-a1bd-a87b738a7cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group group-nationality&quot;]/div[@class=&quot;input-group form-group&quot;]/div[@class=&quot;country-select inside&quot;]/div[@class=&quot;flag-dropdown&quot;]/ul[@class=&quot;country-list&quot;]/li[@class=&quot;country preferred active highlight&quot;]/span[@class=&quot;country-name&quot;]</value>
      <webElementGuid>9ef3533a-4944-4091-b745-4463971d22af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal_info_part']/form/div[6]/div/div/div/ul/li/span</value>
      <webElementGuid>64423349-4089-4cfc-8bb2-f081a702ac83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nationality'])[1]/following::span[1]</value>
      <webElementGuid>3ecffc52-77a3-4510-95a8-ee91088adb69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zimbabwe'])[1]/following::span[1]</value>
      <webElementGuid>3b7c4b8a-376d-48ee-98f1-37d6f5107f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesian'])[1]/preceding::span[1]</value>
      <webElementGuid>8b6d331d-cfbe-4199-96c2-64aea4873a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysian'])[1]/preceding::span[2]</value>
      <webElementGuid>9b6b2158-0af4-4fe3-987a-fd9fb306ed11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Singaporean']/parent::*</value>
      <webElementGuid>2d4d6642-12fa-479e-a789-06f842ce32e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/ul/li/span</value>
      <webElementGuid>68fa3ebf-b5fc-448b-97e6-70d6cb484e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Singaporean' or . = 'Singaporean')]</value>
      <webElementGuid>e4105129-bed6-48b4-b9b1-ed86027e2cb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
