<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>manual_gender-female</name>
   <tag></tag>
   <elementGuidId>8c8227f6-4f58-4b64-82c2-cc157eb775b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='personal_info_part']/form/div[3]/div/label[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0088c49b-9005-4393-80a4-be2df61f53ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>b72d9c1c-e718-4c73-9226-cf390dbd2b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>f5b221b1-3893-4f01-bf87-cb1cb39882db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>42777a49-43bc-4e9b-aa4b-875eba8e8d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1007968b-7b50-4441-9b83-37fbf9bf0e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>b6062fb7-303d-4f7d-bfb6-13b16accc539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>8fe6a088-26af-4128-a5bb-c2be4e09fce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>c6395a79-4610-44fe-b57e-4bd6120b8753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>502977b5-0329-457a-b47b-8a64b1939051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>9322fbec-a937-4c5e-a29f-9ea79d6e9595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>dac8103c-109d-4feb-9ee8-9e9ac7c3792a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>04e23d4e-4f0c-4f76-a928-afee7e309394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e20c0d47-3dff-40fd-aca9-435c0b1debb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>bebe2c6b-f7ca-4f9e-a731-2f133b1db8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>636cf984-1e41-442b-8f75-dedc7f789f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>bde441e9-e10c-47d4-9322-46da6ff0f829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>81e500ab-9aea-41fd-a54c-e18b042b102a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>2d51b1f8-49b9-4632-b346-0adee60309a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>39981d64-c5e7-4c7f-beaa-c0ebd5ccbf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>7c0734d4-9595-4cb9-9d1b-6f6acceb534e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d95ab652-859a-4cd9-8cfa-7b1d515aa08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>d36a9435-a0a0-4670-a64c-7727dea2b938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>21928e87-4395-4184-8d14-06f01f82073c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>376db472-a875-4bbc-be57-0b6ad9506394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>77b2ab5c-9e5e-444b-961e-1e39f23b0eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>b7672112-cce2-4b2a-a384-433e1bd3c6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>bb203d70-e360-46c7-8818-bb237556cdff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>ad9b0966-5459-4c8b-9551-d074aa731ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff98a26c-43c1-4c90-a79f-6ec2982a1e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>f282ab15-d4ef-40f5-ab02-36632593c0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>1ba049b0-da8f-4ad1-bd7b-acb610c5ef46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>c5253521-2ac1-4e89-921f-a6b8e4b55abe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal_info_part']/form/div[3]/div/label[2]/div/div</value>
      <webElementGuid>5153ebe5-4e03-428f-be8b-70c2b38ba927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[1]/following::div[2]</value>
      <webElementGuid>1eb80319-4f34-46d6-8705-fa97654b7186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::div[5]</value>
      <webElementGuid>e1eb9664-68d4-4c2c-9348-67dd6c8c3fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/preceding::div[1]</value>
      <webElementGuid>bd44f4d6-59e1-4c02-ac84-5ab6a7ea8fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div/div</value>
      <webElementGuid>ca2086bb-eb6d-49c2-a045-fdd653255e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Female' or . = 'Female')]</value>
      <webElementGuid>222be8ff-4144-4222-9232-29a7fb22e3a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
