<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>manual_li_Indonesia62</name>
   <tag></tag>
   <elementGuidId>2fec306c-99d1-4f86-a91d-0e66de20563c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='iti-0__item-id-preferred']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iti-0__item-id-preferred</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>394190a2-9b8e-472a-85f5-7cecc794bce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country iti__preferred iti__highlight</value>
      <webElementGuid>ccf6c26a-4226-42d0-a004-652c932d3c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c7016c7a-7b32-4b0e-9e1a-9f85af099921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iti-0__item-id-preferred</value>
      <webElementGuid>f2ed4d92-9750-4021-8f42-a1c4d6317070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>240bb407-9993-4c8e-8fb3-79aaf7c9ff53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>26fb7fb3-e6b5-431a-8973-7b19cba5e021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>f23f929e-ebb3-42fc-850a-4cde7d5f8e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia+62</value>
      <webElementGuid>46a6c3e3-f780-46e5-83df-68ae6b11478e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-0__item-id-preferred&quot;)</value>
      <webElementGuid>3e7c1b59-48bb-4582-a27e-cd4d4f6ed1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8c42b7c5-5aa0-495d-a360-d67d3a5e1a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country iti__preferred iti__highlight</value>
      <webElementGuid>f9aa7aa4-0162-4f64-b0c2-9bf24fc59587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>da7ccc21-1cc7-432b-a197-97a028739433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iti-0__item-id-preferred</value>
      <webElementGuid>464e6efd-e6e7-4f01-9be0-0c6b1818f224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2448c9fc-d29e-46c4-abb2-a89ee47934c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>8d09eb36-c1dd-4b75-b87c-e2f87a8ad612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>e8ceb082-6962-414a-858b-22413510175d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia+62</value>
      <webElementGuid>08a3178f-3a93-4cfc-ac65-f54ed970b856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-0__item-id-preferred&quot;)</value>
      <webElementGuid>5a3c1813-6df9-4715-a978-4868c5cd20a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>04ba2917-1fed-46da-8631-cf832e8491e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country iti__preferred iti__highlight</value>
      <webElementGuid>86a69a02-841f-4163-9f12-1582122252f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>94a91bc4-9111-486e-a54a-2dca3d5d247d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iti-0__item-id-preferred</value>
      <webElementGuid>eb325491-7de1-480b-be5c-e74adea4c70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>995b5279-d8e6-4be2-9e1c-e960c5fefb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>bce990e5-b6b6-4590-b9d0-4f42065297ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>6cc39533-aec2-4063-83a3-15ad34f1e599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia+62</value>
      <webElementGuid>e71a3d97-b9df-48fa-9068-07f19eabd225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-0__item-id-preferred&quot;)</value>
      <webElementGuid>05431c13-5b1a-4124-a65c-67756aa5637e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c7388abe-f695-4216-8d86-b5b1db09fa88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country iti__preferred iti__highlight</value>
      <webElementGuid>8c5de67a-3a66-404b-b77e-180d78676bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9c5c5f42-fd32-4013-91bb-447036fa4e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iti-0__item-id-preferred</value>
      <webElementGuid>72abfa33-4939-4b12-a11a-a03dde5ce4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d3e16384-29cc-4166-aaac-787f6d23d19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>e3af99f8-b0b2-4e65-b2bd-f39166234f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>0ead5ae1-d0df-4e50-bb90-14b3b3c2a15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia+62</value>
      <webElementGuid>ca26ab6a-7537-4abe-9162-cc6496b6db42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-0__item-id-preferred&quot;)</value>
      <webElementGuid>a45407db-bcee-4cae-87fb-36ac2b27e18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4d855ff9-e978-4796-8c33-cb2356140923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country iti__preferred iti__highlight</value>
      <webElementGuid>4c705d57-69c4-488b-b21a-162bdb4b5eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7d8f0936-3cd4-4029-b354-0c8359e25e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iti-0__item-id-preferred</value>
      <webElementGuid>9c487f51-dd6d-406f-b46a-a7ed8dcd1874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>31e6e4c2-78e9-42cc-a78c-fed7eec752cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>6912892d-2598-4dda-9a97-1e1075c6e743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>175db7a0-4942-4c80-833e-bdddf02838e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia+62</value>
      <webElementGuid>ecb4e0e6-040f-45a3-b1d0-f4d45e8a0b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-0__item-id-preferred&quot;)</value>
      <webElementGuid>78de2e46-8cb1-449e-adf0-f4130de06584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>14a442dc-edc3-4a0a-8ad7-ef41b331d491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country iti__preferred iti__highlight</value>
      <webElementGuid>31c33d5a-4a99-4574-bb61-1434f675a9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2e23c839-f12d-4f70-a98d-9c22c5be30fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iti-0__item-id-preferred</value>
      <webElementGuid>d6e04390-e83f-486d-b8ab-c914c132a7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bd123ee7-009d-4756-92e9-13cfab707e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>bc1534b3-5737-46f7-9ae7-b71d3c6e373c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>a481de6c-5f76-4b24-81bd-774356d98262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia+62</value>
      <webElementGuid>b534e1c7-6661-471d-af98-b7f0ac1e5577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-0__item-id-preferred&quot;)</value>
      <webElementGuid>18b2a36f-9fe2-46ec-8de5-ecb7e116ec59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e6a533a2-35e7-4dae-a53c-bd6a7c3f4c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country iti__preferred iti__highlight</value>
      <webElementGuid>670f75f1-3649-4340-8cbf-60734f1d35fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4c058dce-12ca-4e84-812f-cfd63f4c3b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iti-0__item-id-preferred</value>
      <webElementGuid>e269dc7a-2805-4222-9252-5dfa15262992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>74f2eec0-c041-4038-a4db-bb81587020a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>ca79200d-2b42-43f8-962f-42fd0c57aee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>2d98038b-c8c7-4317-b184-06191ffa372e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia+62</value>
      <webElementGuid>208f3492-69b9-4015-a600-5efa1b34fd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-0__item-id-preferred&quot;)</value>
      <webElementGuid>e5eb2661-f8e9-401a-aeb8-a6d89a10b249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>87b57d85-9d34-4bf1-8b10-74565a0a2183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country iti__preferred iti__highlight</value>
      <webElementGuid>5caba6dc-c69d-4efc-8b15-8e38fcc41cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0787100a-3f05-4fce-8945-1023d6b4be56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iti-0__item-id-preferred</value>
      <webElementGuid>5128f734-16c5-47fd-a991-797cc2c5b749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5519b9ac-fa5c-4d72-84a4-3126d78286d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>a996f97a-9170-4271-8af8-bbef2ed08c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>edbf1f5d-a141-4266-802b-9cf664abdbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia+62</value>
      <webElementGuid>bde18b77-b980-44ff-83a9-7d94d1122e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-0__item-id-preferred&quot;)</value>
      <webElementGuid>773c195f-1078-460d-a8a4-3e3707054c62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='iti-0__item-id-preferred']</value>
      <webElementGuid>72c8aa7a-6900-42e3-8bf0-7ffb9b4e9abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='iti-0__country-listbox']/li[2]</value>
      <webElementGuid>25fb15ff-7fb5-4ca9-98d9-526704941f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore'])[3]/following::li[1]</value>
      <webElementGuid>cb74cc60-1181-49b4-b50b-f3b6bd7b7f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::li[2]</value>
      <webElementGuid>c54a954e-40e2-4bee-a41e-85c67c563347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia'])[3]/preceding::li[1]</value>
      <webElementGuid>f300d960-da00-4318-a395-c800641ed7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/ul/li[2]</value>
      <webElementGuid>0c3e855e-d8a9-4591-a810-2674ade86497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'iti-0__item-id-preferred' and (text() = 'Indonesia+62' or . = 'Indonesia+62')]</value>
      <webElementGuid>0e224d61-c268-46f0-8557-f667d777483c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
