<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>manual_gender-male</name>
   <tag></tag>
   <elementGuidId>bf95308b-8f15-4554-96bb-e1959cce2e32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='personal_info_part']/form/div[3]/div/label/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.box-disabled.border-primary.fw-mh.d-flex.flex-column.justify-content-center.align-items-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ec78f4e-e5f1-4f08-8288-99c8de62203b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>86c24f9f-30ec-4c85-9c98-93d25a134bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>f98e1fc0-7ead-4d53-b316-1c73eda59d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>374a7474-72ab-4574-b3e1-e49abcd1629b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5e1b59c-6593-4691-81f2-b1adb89ea8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>6a901622-6599-4c46-a313-683e4ca22c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>7a542549-9c9d-49e8-99b5-aaa98fd2067f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>d6a294ee-e3fb-4ad7-8bca-afe3a55d85ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9cb5c5f4-bc4b-4731-8c43-2c5c268eb0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>8da459e2-b539-4881-81fd-d946bc612ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>5081cf51-81da-4615-b4d1-7b2e43a96353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>2cad4540-2dbb-4423-af4f-598c75d1d296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fcbfd66f-4e62-4fe6-9904-931898c9e56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>30b347ee-b4e3-4d0c-99bd-3fa5deed9efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>627cf238-eb03-46b6-b04a-f950ccaa5e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>5a30ab1b-825d-4ac7-8dec-224b0ab7c9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0af90da4-ccff-4c15-8485-a640c777d4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>48128621-56ba-49fd-804f-d905983d075d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>a5d96ddc-37ac-4951-80e7-bb0208c10eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>f9740d6e-ff62-473e-bfe9-401d90167f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ce07080-23a8-4be2-a185-4b1a2fb706a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>0c883617-b819-4a1c-b89a-54355df0cd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>7881c909-d0fb-413b-aaa9-045a685130ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>0101a0f0-01b2-4447-96ba-d38b98e75b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af187ea0-62fb-44d8-9279-6ec5d1ce3fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>512d4949-14a6-46d2-a1f2-1bebf4352a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>e66cd3c2-ac90-46e2-9569-42aab12dec3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>4341570c-6ef9-44bb-8375-957ab169b620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d1f6aa0-f81d-418d-acee-8ebd86fb8045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>cc1a5c33-d3a7-4d82-894f-ed04061ae092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>6acdfd9f-9279-4e53-ad74-8862e4c4b49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal_info_part&quot;)/form[1]/div[@class=&quot;group&quot;]/div[@class=&quot;gender-box-disabled text-center input-group d-flex flex-row justify-content-between&quot;]/label[@class=&quot;w-50 z-index1&quot;]/div[@class=&quot;form-check-inline w-100&quot;]/div[@class=&quot;box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>f83e2354-8767-427b-b2d4-c4017c15f6b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal_info_part']/form/div[3]/div/label/div/div</value>
      <webElementGuid>6369dcd8-88ef-46cd-9786-ade16c20cf4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::div[3]</value>
      <webElementGuid>df89519d-218a-4a00-8171-5bc2628d388a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::div[4]</value>
      <webElementGuid>61ee59bd-80fe-436b-8f03-cccdb07a52de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/preceding::div[1]</value>
      <webElementGuid>47b857a9-dc5e-4851-9211-10a5c4ec28db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div</value>
      <webElementGuid>19261ff7-6844-4bab-8eb7-f70cf53668cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Male' or . = 'Male')]</value>
      <webElementGuid>aabaf186-8c56-490c-8ddf-338be60ddb36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
