<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NRICFIN Passport</name>
   <tag></tag>
   <elementGuidId>fe6c0b9d-975b-4762-8400-f23403e5d10a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idNumberType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='idNumberType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>48e707eb-b72a-4b89-b20d-2c54ad9dca22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>idNumberType</value>
      <webElementGuid>2b373b84-d2e7-495b-9ed0-70a9ca2b631e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idNumberType</value>
      <webElementGuid>3487e2c2-f8fb-4a30-8a3b-39db9f01eb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ID Number Select</value>
      <webElementGuid>5b635395-a9f2-4db6-9ffa-0b0d14319922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-select-lg</value>
      <webElementGuid>27c0e642-7733-4d06-8b02-5d0b317fc2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NRIC/FIN Passport</value>
      <webElementGuid>d5996013-54fe-40f3-ae64-641144e5cfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idNumberType&quot;)</value>
      <webElementGuid>c018b1ba-c2c7-47cd-a8e8-5ff877cbb5b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='idNumberType']</value>
      <webElementGuid>e6efb996-23c9-443e-8237-65852bc47325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal_info_part']/form/div[7]/div/div/div/select</value>
      <webElementGuid>298933b9-118a-4759-bed7-2dad1a72008b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wrong ID may result in missing results.'])[1]/following::select[1]</value>
      <webElementGuid>f2828658-1373-4b44-94d9-1719772ff0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Number'])[1]/following::select[1]</value>
      <webElementGuid>229a8bca-5564-4172-bd6f-f368cbfea6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/preceding::select[1]</value>
      <webElementGuid>962e4b2a-b446-45df-8779-94f1348b1777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore'])[3]/preceding::select[1]</value>
      <webElementGuid>491580a7-1c96-4270-86ed-2d05a6097ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5d1ba1fa-b42f-4bc2-adee-668f70f01aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'idNumberType' and @id = 'idNumberType' and (text() = 'NRIC/FIN Passport' or . = 'NRIC/FIN Passport')]</value>
      <webElementGuid>3fc3c072-0768-40b7-b412-80c16a61a0fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
