<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mh360-image-login-page</name>
   <tag></tag>
   <elementGuidId>cf51c545-b205-44d5-9080-526e50f771e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='login-mh360-image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-mh360-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d460d580-aff4-43bf-bc15-f314b1916437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-mh360-image</value>
      <webElementGuid>ce5cea86-43b6-4aa0-9696-2fe31f390256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/oxauth/ext/resources/images/logo-mh360.png</value>
      <webElementGuid>9b9da5c3-d88b-4149-b07b-a2a35a327f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>47028de0-a91f-401f-b1a3-970a3a5dce1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 mt-4</value>
      <webElementGuid>fb366d3a-7782-4c47-b0d5-f73c49e2d227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-mh360-image&quot;)</value>
      <webElementGuid>bb82c791-57f7-4204-b0b1-0a59de055b48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='login-mh360-image']</value>
      <webElementGuid>7c904ff8-9d66-4554-9b9c-21c8c7423e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/img</value>
      <webElementGuid>31bcdb63-a46f-4c6f-a6a9-8c6aaf8d61a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'login-mh360-image' and @src = '/oxauth/ext/resources/images/logo-mh360.png']</value>
      <webElementGuid>cc106c35-c327-4d37-8192-8d661f05cf18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
