<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MyHealth360 Data Privacy Policy</name>
   <tag></tag>
   <elementGuidId>d9c757d2-bc18-4d51-a7a9-66a526495603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prp-myinfo-protection-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='prp-myinfo-protection-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76943bb9-dd80-4a18-9d18-f9d6c68f7dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>7b08ea0c-62b5-4305-b2a0-4160ec2fa18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ihhhealthcare.com/singapore/MyHealth360-data-protection-notice</value>
      <webElementGuid>1b1aa45d-8430-411c-a777-259ba6a24f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-myinfo-protection-link</value>
      <webElementGuid>68b3920d-ac02-4f3e-b056-9adf0fe7614b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dh-link</value>
      <webElementGuid>d33c9b4a-3f02-44b6-b896-fca5e8dcd6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MyHealth360 Data Privacy Policy</value>
      <webElementGuid>b6675fcf-4aa4-4a3c-b90c-338337d51254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-myinfo-protection-link&quot;)</value>
      <webElementGuid>133e2af1-e4d9-41a2-8e78-8bafca2e8385</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='prp-myinfo-protection-link']</value>
      <webElementGuid>457d68d0-0ab4-4bca-a209-111866124b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='prp-paragraph-description']/a</value>
      <webElementGuid>a49d8be3-4e23-4a5e-9da0-30286eb5c9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MyHealth360 Data Privacy Policy')]</value>
      <webElementGuid>eb6eef69-3b91-451f-9f47-d6a05ed69f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accept and Continue'])[1]/following::a[1]</value>
      <webElementGuid>ad0affb3-ab26-430d-bc9f-3272c8ec4843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[1]/following::a[1]</value>
      <webElementGuid>2af0b729-66da-4178-ba78-cf9d43fd0cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'prp-myinfo-protection-link', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>8463aa6b-a796-497b-8436-ea1652145ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MyHealth360 Data Privacy Policy']/parent::*</value>
      <webElementGuid>4dcf3250-0a3b-4d25-9093-670cbe8af555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.ihhhealthcare.com/singapore/MyHealth360-data-protection-notice')]</value>
      <webElementGuid>6219f777-916f-4402-9724-b79eb8e20d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>c197e8f8-58a1-4b17-b3e8-f1c72bff7e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ihhhealthcare.com/singapore/MyHealth360-data-protection-notice' and @id = 'prp-myinfo-protection-link' and (text() = 'MyHealth360 Data Privacy Policy' or . = 'MyHealth360 Data Privacy Policy')]</value>
      <webElementGuid>b6d8ce4a-acac-4018-9d8c-bf5570072e25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
