<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept and Continue</name>
   <tag></tag>
   <elementGuidId>e15fb5dd-98f6-4e88-97e6-0c49e0cc4c83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prp-btn-submit1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='prp-btn-submit1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a98f1321-f749-45b5-99ad-8c13a1e0488e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4eb66724-2cd9-4f31-bb31-650fb1227874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-btn-submit1</value>
      <webElementGuid>e7a6e950-6f24-40f3-8edc-09910f37b11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary text-white</value>
      <webElementGuid>7cfe0489-9a4d-41d9-aee6-437737468c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept and Continue</value>
      <webElementGuid>378126e9-37a1-48b7-aad5-acedb61336ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-btn-submit1&quot;)</value>
      <webElementGuid>cd787193-9552-4deb-a007-d456e3e3e3f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='prp-btn-submit1']</value>
      <webElementGuid>d951cc90-5c7f-455a-a57b-f0c0ac2317b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-section']/div[4]/button</value>
      <webElementGuid>fc116992-ec76-4bc0-a83c-3ad8c27fab79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[1]/following::button[1]</value>
      <webElementGuid>3246abde-3898-4871-bf0f-3001b56ad386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='myinfo95463@gmail.com'])[1]/following::button[1]</value>
      <webElementGuid>0224efe8-b70a-4c8e-b355-44c8f3af454b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyHealth360 Data Privacy Policy'])[1]/preceding::button[1]</value>
      <webElementGuid>b808de87-b882-4301-a4d9-26cfe4a1e506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'prp-btn-submit1', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>281aeb0e-3a1c-49ef-88d9-056129bfca70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept and Continue']/parent::*</value>
      <webElementGuid>090474bd-9fb8-4b28-b6eb-8b48fab2e5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>340c2f8a-0c46-468a-bf73-4d9a21c398f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'prp-btn-submit1' and (text() = 'Accept and Continue' or . = 'Accept and Continue')]</value>
      <webElementGuid>ccb99d12-f3cd-4810-a023-e0f147ad1191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
