<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign-up Successful</name>
   <tag></tag>
   <elementGuidId>890299f3-3c1d-4e48-b60b-317ab19c63b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-success']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-body.text-center.pb-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>72e0e551-22e7-4043-bea5-4fd22f4983e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-center pb-5</value>
      <webElementGuid>2f6e9ea6-67bf-4d91-be38-d0112db3ecfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign-up Successful</value>
      <webElementGuid>c6541ace-8bb8-428a-ab7a-09e86f694c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-success&quot;)/div[@class=&quot;modal-dialog modal-dialog-mh modal-dialog-centered mx-auto&quot;]/div[@class=&quot;modal-content modal-content-mh&quot;]/div[@class=&quot;modal-body text-center pb-5&quot;]</value>
      <webElementGuid>34d0ca68-e7a9-4167-81b8-70942c31a1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a799f518-5809-409e-bf79-2cd1a499cf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-center pb-5</value>
      <webElementGuid>442e49f4-9b8f-4c54-bb4e-0d035d4202fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign-up Successful</value>
      <webElementGuid>12ba312e-f12e-4509-8ddf-3c3ca084e3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-success&quot;)/div[@class=&quot;modal-dialog modal-dialog-mh modal-dialog-centered mx-auto&quot;]/div[@class=&quot;modal-content modal-content-mh&quot;]/div[@class=&quot;modal-body text-center pb-5&quot;]</value>
      <webElementGuid>a90d4373-53a7-4755-b2e4-ccf500721861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53ee3288-c7a2-495d-86fe-56440e56168a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-center pb-5</value>
      <webElementGuid>224baf46-449c-4853-9408-9e46788e971d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign-up Successful</value>
      <webElementGuid>efd2617f-aa50-4a22-9f31-7de1e0448e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-success&quot;)/div[@class=&quot;modal-dialog modal-dialog-mh modal-dialog-centered mx-auto&quot;]/div[@class=&quot;modal-content modal-content-mh&quot;]/div[@class=&quot;modal-body text-center pb-5&quot;]</value>
      <webElementGuid>ab260cbf-1f0c-4d3a-a6b2-f1c5614965a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>15ce0e87-820b-400a-9c9a-55048793fd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body text-center pb-5</value>
      <webElementGuid>65969b65-f113-4a56-9888-cadc115c6c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign-up Successful</value>
      <webElementGuid>207709e0-c63a-4b52-92b0-5fc80424990b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-success&quot;)/div[@class=&quot;modal-dialog modal-dialog-mh modal-dialog-centered mx-auto&quot;]/div[@class=&quot;modal-content modal-content-mh&quot;]/div[@class=&quot;modal-body text-center pb-5&quot;]</value>
      <webElementGuid>bee08d9a-4848-4d86-b1a3-8f7b7aed6fcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-success']/div/div/div[2]</value>
      <webElementGuid>866511af-b889-41b5-bbd9-b202c8060798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error occured'])[1]/preceding::div[4]</value>
      <webElementGuid>f756d9f2-8c03-47b1-8bc4-c248dac8c0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]</value>
      <webElementGuid>95fb50bc-6508-4c44-bb8e-70331127deee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Sign-up Successful' or . = ' Sign-up Successful')]</value>
      <webElementGuid>6f8428b3-7c65-4591-b8f8-4d99e4dfe4dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
