<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please provide a valid number</name>
   <tag></tag>
   <elementGuidId>1cc86bdc-a401-4239-8ea6-1329821bce57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Zimbabwe'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prp-helper-input-phone-required</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb612ce9-cfef-4dee-8ace-14810cacb641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-helper-input-phone-required</value>
      <webElementGuid>8481a9cb-33bd-48e0-8858-3b0fdbc33ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-small invalid-feedback text-left d-block</value>
      <webElementGuid>ef72aaf6-ca50-4ce1-b0c2-3b34faba7be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please provide a valid number.
                                    </value>
      <webElementGuid>c2bdf81d-a2aa-47ad-a5e0-08a7202aea1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-helper-input-phone-required&quot;)</value>
      <webElementGuid>0a760382-5a1b-4c98-a8d1-d6573829ff99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='prp-helper-input-phone-required']</value>
      <webElementGuid>6dfe89ea-6264-43af-990f-817ae8a27675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-phone']/div[2]</value>
      <webElementGuid>c96e79d5-b5a3-4be6-ae3c-be0ef38553dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zimbabwe'])[1]/following::div[1]</value>
      <webElementGuid>021fd183-1cf5-4e65-a6a1-cb4093a1e4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zambia'])[1]/following::div[3]</value>
      <webElementGuid>50af1fee-15e3-47be-b2df-e53bfcea5632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::div[5]</value>
      <webElementGuid>b3466019-98e5-48e7-9728-720225bdb438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'prp-helper-input-phone-required', '&quot;', ')')])[1]/preceding::div[6]</value>
      <webElementGuid>6a3e2bf0-3618-447b-86ef-7da2497d9e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please provide a valid number.']/parent::*</value>
      <webElementGuid>eaed08ca-96a6-4f7c-b61d-213710ce1c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>19a0679f-6241-4126-8130-a6d6cf4ca69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'prp-helper-input-phone-required' and (text() = 'Please provide a valid number.
                                    ' or . = 'Please provide a valid number.
                                    ')]</value>
      <webElementGuid>8e0b9f8f-5a2a-461d-9b94-afa6e7a0d53f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
