<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mobile No_iti__arrow iti__arrow--up</name>
   <tag></tag>
   <elementGuidId>70ac9cf3-d855-40bf-9c2c-08decbcaed38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.iti__arrow.iti__arrow--up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='group-phone']/div/div/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>440d0267-7559-40b5-bc17-99ff4b80d0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__arrow iti__arrow--up</value>
      <webElementGuid>f59bda4e-8ed2-4367-bdfd-5eed9491dfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-phone&quot;)/div[@class=&quot;input-group&quot;]/div[@class=&quot;iti iti--allow-dropdown iti--separate-dial-code&quot;]/div[@class=&quot;iti__flag-container&quot;]/div[@class=&quot;iti__selected-flag&quot;]/div[@class=&quot;iti__arrow iti__arrow--up&quot;]</value>
      <webElementGuid>9c9bd233-96b5-443e-8132-e5557d69c29e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-phone']/div/div/div/div/div[3]</value>
      <webElementGuid>9dd08344-ce18-484b-b607-75b71eee08b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[3]</value>
      <webElementGuid>5b54bbdd-6136-4637-b559-1089884a1c5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
