<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_reCAPTCHA_recaptcha-checkbox-border (2)</name>
   <tag></tag>
   <elementGuidId>ddaa11ea-2356-43f7-b608-2ecce6bb38e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.recaptcha-checkbox-border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='recaptcha-anchor']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ae7378d-6b36-4f8a-ae08-aaf3e9288f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recaptcha-checkbox-border</value>
      <webElementGuid>2ca413c2-e4e2-4d3c-bf51-ef54e5c9f8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>96972d39-366c-45d1-9870-8ced0bbaa2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-anchor&quot;)/div[@class=&quot;recaptcha-checkbox-border&quot;]</value>
      <webElementGuid>375c0f8a-02cf-49ab-a722-f9070b2179a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_My Info/iframe_Zimbabwe_a-fxl6ug88w7hc_1</value>
      <webElementGuid>eb8240c3-a321-4bc2-a9ce-c5fe16b9939f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='recaptcha-anchor']/div</value>
      <webElementGuid>8a832a18-0978-479b-a494-4cb8b0ce560f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>729695a7-1de6-4585-9f33-4d8926fd4d6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
