<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Error occured_container container-dh mx-auto</name>
   <tag></tag>
   <elementGuidId>a53ddd4d-cfe8-4fc8-99fd-791cbaacedc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container.container-dh.mx-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myinfo']/div[3]/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>33c45e82-470a-4510-af8d-0849a35a8024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container container-dh mx-auto</value>
      <webElementGuid>3ddaaeee-4d2c-476b-b6a4-7acad2065cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myinfo&quot;)/div[@class=&quot;layout-box&quot;]/div[@class=&quot;col mx-auto&quot;]/div[@class=&quot;card border-0 px-3&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-flex justify-content-center myinfo-content mx-auto&quot;]/div[@class=&quot;container container-dh mx-auto&quot;]</value>
      <webElementGuid>d2ce3bfd-c667-451c-bb32-aa32122cbddc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myinfo']/div[3]/div/div[2]/div/div/div</value>
      <webElementGuid>3e6a4ad3-a522-4c6f-b1bd-eaa67709078e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error occured'])[1]/following::div[7]</value>
      <webElementGuid>8e62762b-1344-4b1a-951c-09b00955001a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign-up Successful'])[1]/following::div[13]</value>
      <webElementGuid>7877b9c3-7834-4984-bfce-a3eeb234db7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review My Profile'])[1]/preceding::div[6]</value>
      <webElementGuid>4ddcee3f-416a-4fd8-8c44-62bc1922e900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Name'])[1]/preceding::div[7]</value>
      <webElementGuid>0593f205-9fab-476a-80c6-5d6a0e5fcc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div</value>
      <webElementGuid>a4bf0a97-8098-4c05-8a0f-60b72b766da0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
