<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Zimbabwe_a-fxl6ug88w7hc</name>
   <tag></tag>
   <elementGuidId>951a2c54-1eb1-4e74-8953-6330d33e3aaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-fxl6ug88w7hc&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-fxl6ug88w7hc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8200e6c5-29fb-400a-85f4-b7a2efadb73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>d5df6418-43eb-4f07-9ffe-9fc86c359baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA&amp;co=aHR0cHM6Ly9nbHV1LXBwbC5hemxhYnMuc2c6NDQz&amp;hl=en&amp;v=Ixi5IiChXmIG6rRkjUa1qXHT&amp;size=normal&amp;cb=o1vk28i3tvyf</value>
      <webElementGuid>76fc0ffb-a050-4a00-bdc5-0bfe4f982da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>d408749b-c2a2-4bf7-8491-c936275ec30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>8667efb0-dd96-4737-9394-6bdd319f2bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>b1a090b8-59b9-44d5-99da-6b9dc20cd4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-fxl6ug88w7hc</value>
      <webElementGuid>80202d6b-3f8d-492d-85e5-2bdb54b0aad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2112f57-8dbd-4a0d-ba06-e7cfc16eed29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d40e8de2-89ef-42f7-9fa9-a934c7bc7751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>9096d729-4639-46d3-8743-c6954ecc8d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-element&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>d724e2e6-68cf-49e7-9434-788b79ac04a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-fxl6ug88w7hc']</value>
      <webElementGuid>0b73d4e6-b1e7-4907-ac5f-02789ceee4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recaptcha-element']/div/div/iframe</value>
      <webElementGuid>8a6fea80-f57a-422c-904f-a0019d8a0c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>df91bbe5-3804-470e-ad00-19fef2fea71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA&amp;co=aHR0cHM6Ly9nbHV1LXBwbC5hemxhYnMuc2c6NDQz&amp;hl=en&amp;v=Ixi5IiChXmIG6rRkjUa1qXHT&amp;size=normal&amp;cb=o1vk28i3tvyf' and @name = 'a-fxl6ug88w7hc']</value>
      <webElementGuid>fb56b2a2-9c44-439b-8796-3a039c3c1e23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
