<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Minimum 8 characters_a-vtpjaiyyfx0l</name>
   <tag></tag>
   <elementGuidId>f60c68bc-77de-4100-856a-2b8f501ff0e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-vtpjaiyyfx0l']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-vtpjaiyyfx0l&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ed2b426c-8ca2-4eb0-bc92-250c411e2130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>51870714-1631-4d17-876c-1de9613e3c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA&amp;co=aHR0cHM6Ly9nbHV1LXBwbC5hemxhYnMuc2c6NDQz&amp;hl=en&amp;v=NJPGLzpIZgjszqyOymHUP0XR&amp;size=normal&amp;cb=jq96smj3psj</value>
      <webElementGuid>5da68465-85ac-4ca9-ab42-79bc0bcf8e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>15e4c5cf-ec0a-49ff-bd7a-e3d2b53726dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>f50685a8-aee3-4ff6-bc34-9502b484762b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>b2d58171-5f4a-49f3-8425-3463791def4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-vtpjaiyyfx0l</value>
      <webElementGuid>925b0cfe-bf60-4df2-b2ba-a0ed9fd2759e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e649c3a2-ab65-45df-8d4d-051221bb175a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c943422c-7311-432d-aa1b-68d505ab260c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>73067eba-0c47-486e-b3cd-3f4239e175ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-element&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>d4c585a6-f48a-454f-8185-80c1bd6b13e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-vtpjaiyyfx0l']</value>
      <webElementGuid>018a835b-1d69-4265-bc49-f1fb7a62d80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recaptcha-element']/div/div/iframe</value>
      <webElementGuid>0e1246e2-e69e-4ccb-aa60-ec7db13a546a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>182357b6-7bbc-41b4-9d99-098235649c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA&amp;co=aHR0cHM6Ly9nbHV1LXBwbC5hemxhYnMuc2c6NDQz&amp;hl=en&amp;v=NJPGLzpIZgjszqyOymHUP0XR&amp;size=normal&amp;cb=jq96smj3psj' and @name = 'a-vtpjaiyyfx0l']</value>
      <webElementGuid>2e1cbfb7-ffdc-4ede-8ac7-7de1fd5a69a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
