<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img-modal-success-singpass</name>
   <tag></tag>
   <elementGuidId>bd949816-2ed3-445b-9ce9-4af57d06eeee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='prp-img-modal-success']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prp-img-modal-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5f3497eb-e614-49d7-9318-993789f0b0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/success.svg</value>
      <webElementGuid>90662f0c-fb5a-46ea-9ea5-ea0a17d2eeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>36abee30-59a3-4c46-9663-864a9a67e46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-img-modal-success</value>
      <webElementGuid>94727550-2544-408b-9e8a-537a149d1cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto</value>
      <webElementGuid>34bf6de3-302c-4fba-85ed-301f9598eaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-img-modal-success&quot;)</value>
      <webElementGuid>41ce3f3f-04e0-4360-b45d-e9be75758437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='prp-img-modal-success']</value>
      <webElementGuid>b28acc26-8464-4042-9999-589f9018bb80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-success']/div/div/div[2]/img</value>
      <webElementGuid>6fa07e75-0dbd-46fe-819e-c615136c2e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>4c5fe072-1f6d-434f-9daa-01bbe6e3c263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/success.svg' and @id = 'prp-img-modal-success']</value>
      <webElementGuid>c90dc204-56da-4a21-8a5c-204e31ad784b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
