<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img-brand-step1-singpass</name>
   <tag></tag>
   <elementGuidId>1139f9c7-561b-4bba-bfe9-9ca3725354d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='prp-img-brand-step1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prp-img-brand-step1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94cc1089-bd1e-484c-bb0f-1051b279c91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/mh360-logo.png</value>
      <webElementGuid>cd942f00-758e-4a03-b6d4-803a44473d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-img-brand-step1</value>
      <webElementGuid>d21f4421-b53b-4a44-90a8-48a45774bf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-img-brand-step1&quot;)</value>
      <webElementGuid>b4df599f-9ac3-41d1-afaa-bccd170cdfdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='prp-img-brand-step1']</value>
      <webElementGuid>728e5c63-8090-478f-b2b1-26f94a8d3e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myinfo']/div[3]/div/div/span/img</value>
      <webElementGuid>d49750f6-8fde-4588-9657-b02a7ab2d1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>278bf972-a7fb-45e6-8bc3-4b2b818580c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/mh360-logo.png' and @id = 'prp-img-brand-step1']</value>
      <webElementGuid>30fc9e6f-47a3-40f0-b230-a991e1e5aa9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
