<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_chimneys_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>aa655dc0-d0c6-4c1c-88d9-bc93aeb79d63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b88c59bc-b380-4aa3-929f-b4aa98a21e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>6e00d488-234e-4b4a-b5a9-a9b07a7491c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AIIukzhCBGlM8gBAXkgyIpS3bqhyapwdE-CqXVvxqh3H_RNMvemIikuNirSHGJzdPXyHQW_FC3Ek8FhISAQ3Xs22RImQO6Q8mcXKpjiKZuzCGVMgVN7wP1UzMacuhWU4UF993QaKSDVjXU4TPJH3H1xPHcjT-V6PsvHQ2NGXpRtDwABJBOsZ9CzASzTBmkzNpFTkmQ_KE9HPBvi2wV5LETO0o-v_kuPnxw&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA</value>
      <webElementGuid>52db2f68-6f34-48db-8725-4dc1a79f353f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>277e335e-613b-4e61-95be-b9b2577fdcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_My Info/iframe_html1body1div7div4iframe1_c-2q2yx04znqpw</value>
      <webElementGuid>89b854c3-05a5-42ee-b23b-2af91c2f6cb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>6d54937b-3c70-40c4-94f7-3d0dc4757336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AIIukzhCBGlM8gBAXkgyIpS3bqhyapwdE-CqXVvxqh3H_RNMvemIikuNirSHGJzdPXyHQW_FC3Ek8FhISAQ3Xs22RImQO6Q8mcXKpjiKZuzCGVMgVN7wP1UzMacuhWU4UF993QaKSDVjXU4TPJH3H1xPHcjT-V6PsvHQ2NGXpRtDwABJBOsZ9CzASzTBmkzNpFTkmQ_KE9HPBvi2wV5LETO0o-v_kuPnxw&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA')])[5]</value>
      <webElementGuid>b386c4b2-f44f-4fe4-a4f7-62e9feeef745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>3965fc27-b232-4080-9b34-d6e6fcef8cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AIIukzhCBGlM8gBAXkgyIpS3bqhyapwdE-CqXVvxqh3H_RNMvemIikuNirSHGJzdPXyHQW_FC3Ek8FhISAQ3Xs22RImQO6Q8mcXKpjiKZuzCGVMgVN7wP1UzMacuhWU4UF993QaKSDVjXU4TPJH3H1xPHcjT-V6PsvHQ2NGXpRtDwABJBOsZ9CzASzTBmkzNpFTkmQ_KE9HPBvi2wV5LETO0o-v_kuPnxw&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA']</value>
      <webElementGuid>7fafed3e-64b7-4943-b2d3-72401a3a11e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
