<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Allow_prp-img-modal-success</name>
   <tag></tag>
   <elementGuidId>920becdf-ff52-46bb-a498-22dec00fe2cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prp-img-modal-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='prp-img-modal-success']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>804dcf12-5e48-445e-8fd2-f1eb36e63000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/success.svg</value>
      <webElementGuid>52e7ef3c-2c51-42ff-b688-aa74d71b6605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c1970abc-c6df-44f4-b5bb-b3768de199ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-img-modal-success</value>
      <webElementGuid>e775a52f-6f36-47f9-9c34-aa0e8e4c3f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto</value>
      <webElementGuid>0aee0518-e0fa-43b5-b770-1f3ab8a62424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-img-modal-success&quot;)</value>
      <webElementGuid>83ee653f-af40-4334-90c8-acc555447686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='prp-img-modal-success']</value>
      <webElementGuid>383408bf-4f21-4c11-a644-924adb5f394e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-success']/div/div/div[2]/img</value>
      <webElementGuid>076b6373-42a8-4a54-a65f-4b7b11b8c115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>d709a04f-24c5-4104-89df-9eaadb5f436c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/success.svg' and @id = 'prp-img-modal-success']</value>
      <webElementGuid>a8af2d28-1aa5-420d-ba47-c02a6f3281b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
