<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bridges_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>f325e2ae-6836-4004-8ec7-10c7f74b101f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1e454420-6343-4f99-a2ed-2a553a60509e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>fd6293c7-9949-4cb0-a573-09e3427d9e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AIIukzhQP5lma1JedsmSI35N-52iMBtJy2ahUTnTTCBmz68X3qztpfLtWApYDYqeVAISmGFwIQejea_yieSBN3UK-VF0r3cHsX60WuT_vp0dx24Il93JXFBEz-ufWW8qmqIDtZnggMH_YaWjOBadNm5k51N6zY8vamAltK0n59SLbx80K_wv8BPdhgh5V9NRubYumOM3yO1K&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA</value>
      <webElementGuid>e6fdd8ee-fecb-415c-86c9-a81dc9a3d30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>43809457-08b6-4372-a460-0e5cecc808bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_My Info/iframe_html1body1div7div4iframe1_c-vtpjaiyyfx0l</value>
      <webElementGuid>d4716339-9711-459b-9321-af339a2defd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>aa3a2177-b8d8-447b-a433-ca8d83f8fb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AIIukzhQP5lma1JedsmSI35N-52iMBtJy2ahUTnTTCBmz68X3qztpfLtWApYDYqeVAISmGFwIQejea_yieSBN3UK-VF0r3cHsX60WuT_vp0dx24Il93JXFBEz-ufWW8qmqIDtZnggMH_YaWjOBadNm5k51N6zY8vamAltK0n59SLbx80K_wv8BPdhgh5V9NRubYumOM3yO1K&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA')])[5]</value>
      <webElementGuid>1dc6b4f6-76ad-490a-92c3-3fa81fd77ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>23dba024-0c97-4205-9ebf-38a27653b36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AIIukzhQP5lma1JedsmSI35N-52iMBtJy2ahUTnTTCBmz68X3qztpfLtWApYDYqeVAISmGFwIQejea_yieSBN3UK-VF0r3cHsX60WuT_vp0dx24Il93JXFBEz-ufWW8qmqIDtZnggMH_YaWjOBadNm5k51N6zY8vamAltK0n59SLbx80K_wv8BPdhgh5V9NRubYumOM3yO1K&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA']</value>
      <webElementGuid>252093d1-2db6-4d07-b713-15ff1a648d29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
