<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>c8e1bd52-4dfa-4cb4-ba2e-ef6cd95bb0c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a3deb3a4-29b3-4fd8-8320-5d017c2d5ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>9e9341b9-319b-4a38-8f89-91130ae69da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AIIukziqi27hFi6zvceBgJ6CcgA-0YD9n_wwntJiWQPZIdwhCyj5dC56yIHuaNGC2OsZUbB9EfCqS-TX4pWAFWvMb3vHKpKWU1YrzIovlySgQmHq3Mv0z0sZS-aevq6yA3A6mjcaQvyRpdcPNWGA8oJWjg0t8eFK2gD_UoW3pnSp3Vp7GGqEynrkDoU0CRPF5-kwoGSZbRIS&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA&amp;id=2</value>
      <webElementGuid>bb072818-c76b-4e1b-8c03-fc53fbb58fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>7ddcc205-a391-4a44-9b70-f2b20089a2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_My Info/iframe_html1body1div7div4iframe1_c-mdi9w0vl37f7</value>
      <webElementGuid>9386b211-3793-48cb-bd0e-9719cab02cfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      <webElementGuid>129685d4-088f-475c-a3de-ad1e35b97e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AIIukziqi27hFi6zvceBgJ6CcgA-0YD9n_wwntJiWQPZIdwhCyj5dC56yIHuaNGC2OsZUbB9EfCqS-TX4pWAFWvMb3vHKpKWU1YrzIovlySgQmHq3Mv0z0sZS-aevq6yA3A6mjcaQvyRpdcPNWGA8oJWjg0t8eFK2gD_UoW3pnSp3Vp7GGqEynrkDoU0CRPF5-kwoGSZbRIS&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA&amp;id=2')])[9]</value>
      <webElementGuid>b03aa3cb-f6c2-48e5-affb-c3179957684f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
      <webElementGuid>d89ef395-551d-4d0f-b90e-3a58d7c690b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AIIukziqi27hFi6zvceBgJ6CcgA-0YD9n_wwntJiWQPZIdwhCyj5dC56yIHuaNGC2OsZUbB9EfCqS-TX4pWAFWvMb3vHKpKWU1YrzIovlySgQmHq3Mv0z0sZS-aevq6yA3A6mjcaQvyRpdcPNWGA8oJWjg0t8eFK2gD_UoW3pnSp3Vp7GGqEynrkDoU0CRPF5-kwoGSZbRIS&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA&amp;id=2']</value>
      <webElementGuid>2b1c4241-ee0f-4363-867d-6464f40d028c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
