<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>17bc237f-3d88-425c-8327-dc8a04e2195e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>08156708-3679-4dc1-97b4-3e767acb8887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>92568b9d-7f68-4953-938c-438d5b544909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AIIukziqi27hFi6zvceBgJ6CcgA-0YD9n_wwntJiWQPZIdwhCyj5dC56yIHuaNGC2OsZUbB9EfCqS-TX4pWAFWvMb3vHKpKWU1YrzIovlySgQmHq3Mv0z0sZS-aevq6yA3A6mjcaQvyRpdcPNWGA8oJWjg0t8eFK2gD_UoW3pnSp3Vp7GGqEynrkDoU0CRPF5-kwoGSZbRIS&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA</value>
      <webElementGuid>4676733c-c4e4-41c2-839d-430d9cce630e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>19db94a0-3b0b-410e-9d61-7110a5e2fb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_My Info/iframe_html1body1div7div4iframe1_c-mdi9w0vl37f7</value>
      <webElementGuid>83cb2783-8e8f-4ad2-aeff-b04d1614bb9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      <webElementGuid>bfa4219f-9130-484c-b8b1-cb89aea545be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AIIukziqi27hFi6zvceBgJ6CcgA-0YD9n_wwntJiWQPZIdwhCyj5dC56yIHuaNGC2OsZUbB9EfCqS-TX4pWAFWvMb3vHKpKWU1YrzIovlySgQmHq3Mv0z0sZS-aevq6yA3A6mjcaQvyRpdcPNWGA8oJWjg0t8eFK2gD_UoW3pnSp3Vp7GGqEynrkDoU0CRPF5-kwoGSZbRIS&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA')])[13]</value>
      <webElementGuid>4c2ac7b9-6a2b-47fb-950b-940f44c680ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/div/img</value>
      <webElementGuid>9c94c8fc-3215-4937-a18e-d02c2f5136fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AIIukziqi27hFi6zvceBgJ6CcgA-0YD9n_wwntJiWQPZIdwhCyj5dC56yIHuaNGC2OsZUbB9EfCqS-TX4pWAFWvMb3vHKpKWU1YrzIovlySgQmHq3Mv0z0sZS-aevq6yA3A6mjcaQvyRpdcPNWGA8oJWjg0t8eFK2gD_UoW3pnSp3Vp7GGqEynrkDoU0CRPF5-kwoGSZbRIS&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA']</value>
      <webElementGuid>5562acfc-c08e-4f43-9140-64e5ab171eb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
