<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Error occured_prp-img-brand-step1</name>
   <tag></tag>
   <elementGuidId>fb95c8d6-de31-406f-9ca6-da229c20255f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='prp-img-brand-step1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prp-img-brand-step1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>15b59dc3-0bd5-4d2c-82eb-e2f1805408ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/mh360-logo.png</value>
      <webElementGuid>1443ad4f-3ade-47af-8b99-584beaec05e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prp-img-brand-step1</value>
      <webElementGuid>9291f1fb-adbc-4ae0-b68c-6c75c5551241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prp-img-brand-step1&quot;)</value>
      <webElementGuid>89aa1b43-d1fd-4536-ae26-513b4e5a18ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='prp-img-brand-step1']</value>
      <webElementGuid>55029eb9-7801-4221-9c32-1b101ff740d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myinfo']/div[3]/div/div/span/img</value>
      <webElementGuid>3a48949d-4a51-407f-bfef-3b1048afdbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/img</value>
      <webElementGuid>c930f82c-0ce6-4ae6-bf3b-e99af7d6e8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/mh360-logo.png' and @id = 'prp-img-brand-step1']</value>
      <webElementGuid>3caba47a-d6fd-4f11-b025-01edba2cae2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
