<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_stairs_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>04b53857-8c9f-46f1-a503-4f79cc2aac93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>61abc461-e05f-4847-b9dd-8723be9a81f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>c9ae9604-8db4-4691-82ca-7dbe631d60fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AIIukzhxOB1TVyrA3Ddm12pTOa9bm_9KKUz673Q8Xo4p2I_k6zqoGQ08dU6OKOWd9EnNvQYEwSGl5-4nC0cig9qgMqd4eTGAkTi0m03yaz4wRpH_q2JHYOHTO02cnWpbUdxM6fzeHEwlIWXefv682xK2oM9khSDytvGDx5X5rwSDQNA9eRz2vYJnXkF_ENPqAjeXacV2SiXn5-bu0MUmq-uReC8m6G3J3Q&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA</value>
      <webElementGuid>bbf3cb16-430e-40f5-9325-6f3948b9c4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>47e7f4c9-9369-4a93-81f0-09e6850a957a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_My Info/iframe_html1body1div7div4iframe1_c-83b05gbzoyud</value>
      <webElementGuid>e85e73ed-cd3b-4d43-afba-8b48914ac1b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      <webElementGuid>0e70af18-6310-440c-b429-7ecdb04051ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AIIukzhxOB1TVyrA3Ddm12pTOa9bm_9KKUz673Q8Xo4p2I_k6zqoGQ08dU6OKOWd9EnNvQYEwSGl5-4nC0cig9qgMqd4eTGAkTi0m03yaz4wRpH_q2JHYOHTO02cnWpbUdxM6fzeHEwlIWXefv682xK2oM9khSDytvGDx5X5rwSDQNA9eRz2vYJnXkF_ENPqAjeXacV2SiXn5-bu0MUmq-uReC8m6G3J3Q&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA')])[7]</value>
      <webElementGuid>79f3b957-16ca-4cbc-ae66-c8eb46bc4654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
      <webElementGuid>2d9237c0-e707-4789-866f-99f7b27642d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AIIukzhxOB1TVyrA3Ddm12pTOa9bm_9KKUz673Q8Xo4p2I_k6zqoGQ08dU6OKOWd9EnNvQYEwSGl5-4nC0cig9qgMqd4eTGAkTi0m03yaz4wRpH_q2JHYOHTO02cnWpbUdxM6fzeHEwlIWXefv682xK2oM9khSDytvGDx5X5rwSDQNA9eRz2vYJnXkF_ENPqAjeXacV2SiXn5-bu0MUmq-uReC8m6G3J3Q&amp;k=6LfNxmoiAAAAAFPBQdmrFoJH_AyZks-8q5DIWRhA']</value>
      <webElementGuid>5dcb2423-236f-4257-82a0-3a2a979eb9ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
