<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_A one-time PIN has been sent via SMS _fd653b</name>
   <tag></tag>
   <elementGuidId>68691fa1-c5bd-4255-b0c7-261d0bb31d3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otp0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8aaae685-b2b8-4ed2-ac7d-2eaaf037925b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp0</value>
      <webElementGuid>0d28e5f9-6081-4976-be79-6af99eb570b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>6823c995-39cc-4226-aabc-9f348a3f4465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>f3da98f6-538d-479f-aa28-5efab737d845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>893e67a1-9be9-4c24-b74b-96312a50f64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>digit-group-single fw-600</value>
      <webElementGuid>13faf07b-ebae-4e9c-93e1-d6123535379d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp0&quot;)</value>
      <webElementGuid>b0ee2add-c764-4747-a037-9ee21203cb7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp0']</value>
      <webElementGuid>ea76b33b-85cd-4446-a7e0-fd9169ae0343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OTPInput']/input</value>
      <webElementGuid>bb50cbcf-e1d3-4dc7-9076-f91769d64c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2d39eb4a-f1e3-4d02-ba88-e3074b2cff96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'otp0' and @type = 'tel']</value>
      <webElementGuid>736eadbf-eaff-4a0e-8d46-67b1d98ec4f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
