<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Indonesia62</name>
   <tag></tag>
   <elementGuidId>699d8eb0-6c26-4bd0-9bd1-0407dc07a1cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iti-0__item-id-preferred</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='iti-0__item-id-preferred']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>033822e0-557e-4d59-86f2-da42c2523440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country iti__preferred iti__highlight</value>
      <webElementGuid>f06d90a2-6d31-44a7-ad8c-8fb6c1b884b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d84f64be-a94a-480b-a42a-db4442c05d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iti-0__item-id-preferred</value>
      <webElementGuid>31db32c6-88fa-4d6c-849b-e43109b425a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9a4d9960-2d3d-4ec7-a465-121da4da153f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>59e556e0-1518-416d-ac8f-eca96691d2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>b15c25b0-4052-4063-b9a2-502736c6cde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia+62</value>
      <webElementGuid>5812d931-757d-4aa7-b696-78bcbd794640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-0__item-id-preferred&quot;)</value>
      <webElementGuid>943df1dc-959a-49a6-afef-63c97e94182b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='iti-0__item-id-preferred']</value>
      <webElementGuid>5baac678-ab25-4bd2-8486-713dfc026407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='iti-0__country-listbox']/li[2]</value>
      <webElementGuid>419e0e7f-eb0d-460f-8637-de458ca93554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore'])[1]/following::li[1]</value>
      <webElementGuid>feb27636-80b7-4875-8fa2-c1c8ef70430b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile No.'])[1]/following::li[2]</value>
      <webElementGuid>ae6bf172-771d-41b1-b855-911fc24583ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia'])[1]/preceding::li[1]</value>
      <webElementGuid>6c9f43e0-edc1-4569-858e-9f600a83b6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>76a771fe-e773-44bb-9e5c-10087f045f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'iti-0__item-id-preferred' and (text() = 'Indonesia+62' or . = 'Indonesia+62')]</value>
      <webElementGuid>b2caf110-287a-405f-b238-68bbf796bf13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
