<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_This digital service is requesting the _98b49d</name>
   <tag></tag>
   <elementGuidId>9eb51a2c-6493-4cef-b9dd-ff3806051b9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.main-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>54f89d99-d874-4ea7-b86f-d67cb77bfaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-logo</value>
      <webElementGuid>20e2c4a6-b10d-4fd3-8a62-14dbe22a0c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test.consent.myinfo.gov.sg/consent-page-template/images/myinfo-com/singpass-logo.png</value>
      <webElementGuid>1a54e493-b0c3-45c5-b614-ce232b481f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>12724e8e-253d-488e-b11d-0f7b3385a4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;header-container&quot;]/img[@class=&quot;main-logo&quot;]</value>
      <webElementGuid>52641ca8-29ea-4602-9024-71e48cf03826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/img</value>
      <webElementGuid>9437652b-52dd-492c-8e27-a94bf740852f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>6664dbd4-4169-4f1e-b583-c1e626bf9260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>07d01f29-3409-4792-8524-9055a02f98a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://test.consent.myinfo.gov.sg/consent-page-template/images/myinfo-com/singpass-logo.png' and @alt = 'logo']</value>
      <webElementGuid>961e5536-e4dc-4162-8e3b-fe5b192f0783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
