<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CcAdNbmarginauto.QCzoEcmargin-top3pxcol_f902b5</name>
   <tag></tag>
   <elementGuidId>1a4f4cbd-337b-4162-a643-c0752b06a3a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.SDkEP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>babb0979-e21c-426c-870b-422013176610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SDkEP</value>
      <webElementGuid>da96a76d-edfe-43e8-bc27-58bc56e5e934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.CcAdNb{margin:auto}.QCzoEc{margin-top:3px;color:#9aa0a6}.gLFyf,.YacQv{height:34px;}.gLFyf{background-color:transparent;border:none;margin:0;padding:0;color:rgba(0,0,0,.87);word-wrap:break-word;outline:none;display:flex;flex:100%;-webkit-tap-highlight-color:transparent;margin-top:-37px;font-size:16px;}.a4bIc{display:flex;flex:1;flex-wrap:wrap}.YacQv{color:transparent;flex:100%;white-space:pre;font-size:16px;}.YacQv span{background:url(&quot;/images/experiments/wavy-underline.png&quot;) repeat-x scroll 0 100% transparent;padding:0 0 10px 0;}.dRYYxd{display:flex;flex:0 0 auto;margin-top:-5px;align-items:stretch;flex-direction:row}.minidiv .dRYYxd{margin-top:0} .BKRPef{background:transparent;align-items:center;flex:1 0 auto;flex-direction:row;display:flex;cursor:pointer}.vOY7J{background:transparent;border:0;align-items:center;flex:1 0 auto;cursor:pointer;display:none;height:100%;line-height:44px;outline:none;padding:0 12px}.M2vV3{display:flex}.ExCKkf{height:100%;color:#70757a;vertical-align:middle;outline:none}.minidiv .vOY7J{line-height:32px}.minidiv .ExCKkf{width:20px} .BKRPef{padding-right:4px}.ACRAdd{border-left:1px solid #dadce0;height:65%}.ACRAdd{display:none}.ACRAdd.M2vV3{display:block}          .nDcEnd{flex:1 0 auto;display:flex;cursor:pointer;align-items:center;border:0;background:transparent;outline:none;padding:0 8px;width:24px;line-height:44px}.Gdd5U{height:24px;width:24px;vertical-align:middle}.minidiv .nDcEnd{line-height:32px}.minidiv .Gdd5U{width:20px;height:20px}</value>
      <webElementGuid>4147050b-1596-47df-a43d-1edb187cdb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 ikrT4e om7nvf&quot;]/form[1]/div[1]/div[@class=&quot;A8SBwf&quot;]/div[@class=&quot;RNNXgb&quot;]/div[@class=&quot;SDkEP&quot;]</value>
      <webElementGuid>e9f182ca-98f4-4de3-8ab1-25a25e355436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[9]</value>
      <webElementGuid>bba4c1bb-40a5-4c74-9e0b-b3c69482ea85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gambar'])[1]/following::div[13]</value>
      <webElementGuid>7eba28f8-ab4c-4826-86e7-eeba8338040a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::div[20]</value>
      <webElementGuid>a373c00d-69e1-4c8b-9148-cb3b67060340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div</value>
      <webElementGuid>b6314c1a-88e2-4a41-a4af-4e4ad1ecfd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '.CcAdNb{margin:auto}.QCzoEc{margin-top:3px;color:#9aa0a6}.gLFyf,.YacQv{height:34px;}.gLFyf{background-color:transparent;border:none;margin:0;padding:0;color:rgba(0,0,0,.87);word-wrap:break-word;outline:none;display:flex;flex:100%;-webkit-tap-highlight-color:transparent;margin-top:-37px;font-size:16px;}.a4bIc{display:flex;flex:1;flex-wrap:wrap}.YacQv{color:transparent;flex:100%;white-space:pre;font-size:16px;}.YacQv span{background:url(&quot;/images/experiments/wavy-underline.png&quot;) repeat-x scroll 0 100% transparent;padding:0 0 10px 0;}.dRYYxd{display:flex;flex:0 0 auto;margin-top:-5px;align-items:stretch;flex-direction:row}.minidiv .dRYYxd{margin-top:0} .BKRPef{background:transparent;align-items:center;flex:1 0 auto;flex-direction:row;display:flex;cursor:pointer}.vOY7J{background:transparent;border:0;align-items:center;flex:1 0 auto;cursor:pointer;display:none;height:100%;line-height:44px;outline:none;padding:0 12px}.M2vV3{display:flex}.ExCKkf{height:100%;color:#70757a;vertical-align:middle;outline:none}.minidiv .vOY7J{line-height:32px}.minidiv .ExCKkf{width:20px} .BKRPef{padding-right:4px}.ACRAdd{border-left:1px solid #dadce0;height:65%}.ACRAdd{display:none}.ACRAdd.M2vV3{display:block}          .nDcEnd{flex:1 0 auto;display:flex;cursor:pointer;align-items:center;border:0;background:transparent;outline:none;padding:0 8px;width:24px;line-height:44px}.Gdd5U{height:24px;width:24px;vertical-align:middle}.minidiv .nDcEnd{line-height:32px}.minidiv .Gdd5U{width:20px;height:20px}' or . = '.CcAdNb{margin:auto}.QCzoEc{margin-top:3px;color:#9aa0a6}.gLFyf,.YacQv{height:34px;}.gLFyf{background-color:transparent;border:none;margin:0;padding:0;color:rgba(0,0,0,.87);word-wrap:break-word;outline:none;display:flex;flex:100%;-webkit-tap-highlight-color:transparent;margin-top:-37px;font-size:16px;}.a4bIc{display:flex;flex:1;flex-wrap:wrap}.YacQv{color:transparent;flex:100%;white-space:pre;font-size:16px;}.YacQv span{background:url(&quot;/images/experiments/wavy-underline.png&quot;) repeat-x scroll 0 100% transparent;padding:0 0 10px 0;}.dRYYxd{display:flex;flex:0 0 auto;margin-top:-5px;align-items:stretch;flex-direction:row}.minidiv .dRYYxd{margin-top:0} .BKRPef{background:transparent;align-items:center;flex:1 0 auto;flex-direction:row;display:flex;cursor:pointer}.vOY7J{background:transparent;border:0;align-items:center;flex:1 0 auto;cursor:pointer;display:none;height:100%;line-height:44px;outline:none;padding:0 12px}.M2vV3{display:flex}.ExCKkf{height:100%;color:#70757a;vertical-align:middle;outline:none}.minidiv .vOY7J{line-height:32px}.minidiv .ExCKkf{width:20px} .BKRPef{padding-right:4px}.ACRAdd{border-left:1px solid #dadce0;height:65%}.ACRAdd{display:none}.ACRAdd.M2vV3{display:block}          .nDcEnd{flex:1 0 auto;display:flex;cursor:pointer;align-items:center;border:0;background:transparent;outline:none;padding:0 8px;width:24px;line-height:44px}.Gdd5U{height:24px;width:24px;vertical-align:middle}.minidiv .nDcEnd{line-height:32px}.minidiv .Gdd5U{width:20px;height:20px}')]</value>
      <webElementGuid>81f396d8-9f50-48db-9685-a2239b4803c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
