<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Parkway DigiHealth SupportContinue to Chat</name>
   <tag></tag>
   <elementGuidId>f820f99c-0d2c-4d87-8838-6823d8c3eec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main_block']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._9vd6._9t33._9bir._9bj3._9bhj._9v12._9tau._9tay._9u6w._9se-._9u5y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>029b54d1-0479-477a-803c-bafd2ae6782e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9vd6 _9t33 _9bir _9bj3 _9bhj _9v12 _9tau _9tay _9u6w _9se- _9u5y</value>
      <webElementGuid>201badef-afa4-4362-a021-ec29f300f725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Parkway DigiHealth SupportContinue to Chat</value>
      <webElementGuid>5267e4ec-2b8b-4503-a661-afcf068dfe92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_block&quot;)/div[@class=&quot;_9vd6 _9t33 _9bir _9bj3 _9bhj _9v12 _9tau _9tay _9u6w _9se- _9u5y&quot;]</value>
      <webElementGuid>7ff34290-5efc-4644-bd7c-53b0be481b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_block']/div</value>
      <webElementGuid>eab871ac-f447-4229-91fe-fe4b065ec877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get in touch'])[1]/following::div[9]</value>
      <webElementGuid>61f07f96-ecad-48b2-a56b-84d6e8a4bf78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help Center'])[1]/following::div[9]</value>
      <webElementGuid>ac7f2ef8-1b39-42c3-a316-5e1f81df34c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>312eb699-35b6-432d-a3c7-ac32ba19035e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Parkway DigiHealth SupportContinue to Chat' or . = 'Parkway DigiHealth SupportContinue to Chat')]</value>
      <webElementGuid>edc87cbd-5385-4ee1-a937-eacda56d0f6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
