<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_I Agree</name>
   <tag></tag>
   <elementGuidId>7f1fecd8-666e-4422-a0a0-0593634c1f53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#allow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='allow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>209653fa-3029-468d-a50e-412ad6606aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>agree-button</value>
      <webElementGuid>d582e020-1c50-4acc-8211-1019dbdbb8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>allow</value>
      <webElementGuid>025d2e91-b57e-426e-8668-1193eb2294e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>423f56ad-12ea-4769-8fff-2477469e30ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>consent</value>
      <webElementGuid>c398bb7a-b7d1-4029-8d16-466aa965b7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ff69d9d-0187-4de1-83c0-27b0ace32b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I Agree</value>
      <webElementGuid>88a776b6-9832-4b04-b2c3-12161eca863c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allow&quot;)</value>
      <webElementGuid>82b59495-c587-4bd8-851c-c0e323a3e630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='allow']</value>
      <webElementGuid>8ce45bf5-0129-492f-ad1e-7b1aec378639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmConsent']/div[2]/button[2]</value>
      <webElementGuid>a41df169-8c08-46e0-bd66-4c42cc679d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>9c35d28d-24b7-4286-8748-3c53b87897c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Use'])[1]/following::button[2]</value>
      <webElementGuid>500d113e-34a2-4fdd-ab5f-4c7b55690e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'allow', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>d45dd4c8-172e-4934-9d40-9ee46f83f772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I Agree']/parent::*</value>
      <webElementGuid>b813df19-ca1c-44c4-9981-47cba612be73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>bf15f582-a3b0-4045-94a6-2b35eb7e055f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'allow' and @type = 'submit' and @name = 'consent' and (text() = 'I Agree' or . = 'I Agree')]</value>
      <webElementGuid>535fd3da-1dfd-4e9f-b89c-04f3f0d3defc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
