<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Singpass retrieves personal data from r_1df1fb</name>
   <tag></tag>
   <elementGuidId>97b44c14-d41c-43bf-96b8-b787923ac9e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>57d378d6-b126-4e4f-910c-319b4bcd5a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>80e3d5cd-fd09-48e8-ab82-66a62c9b463c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singpass retrieves personal data from relevant government agencies to pre-fill the relevant fields, making digital transactions faster and more convenient.This digital service is requesting the following information from Singpass, for the purpose of Patient RegistrationNameDate of BirthSexNationalityNRIC/FINEmailMobile NumberClicking the “I Agree” button permits this digital service to retrieve your data based on the    Terms of Use.CancelI Agree</value>
      <webElementGuid>aef63f24-d899-47a1-9d8c-b0058afdac62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)</value>
      <webElementGuid>b3d47ba9-e60c-40c1-b4a2-e3c203bee383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>baa4f31d-af6f-47a5-aa11-9d9013c40a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>ceb77692-1054-48c6-9630-be4395a24fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singpass retrieves personal data from relevant government agencies to pre-fill the relevant fields, making digital transactions faster and more convenient.This digital service is requesting the following information from Singpass, for the purpose of Patient RegistrationNameDate of BirthSexNationalityNRIC/FINEmailMobile NumberClicking the “I Agree” button permits this digital service to retrieve your data based on the    Terms of Use.CancelI Agree</value>
      <webElementGuid>d8e4b645-4905-413f-97ad-d6f92130f17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)</value>
      <webElementGuid>b9c051bf-20af-48bb-814c-134dc151a1ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='content']</value>
      <webElementGuid>efbbef33-ad7f-4427-9825-b850b0dd3549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-base']/div</value>
      <webElementGuid>b9964dae-75fd-4ae5-9835-4e6c4f06d458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>1563493b-1e58-46d7-8cdd-a5391b48b1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'content' and (text() = 'Singpass retrieves personal data from relevant government agencies to pre-fill the relevant fields, making digital transactions faster and more convenient.This digital service is requesting the following information from Singpass, for the purpose of Patient RegistrationNameDate of BirthSexNationalityNRIC/FINEmailMobile NumberClicking the “I Agree” button permits this digital service to retrieve your data based on the    Terms of Use.CancelI Agree' or . = 'Singpass retrieves personal data from relevant government agencies to pre-fill the relevant fields, making digital transactions faster and more convenient.This digital service is requesting the following information from Singpass, for the purpose of Patient RegistrationNameDate of BirthSexNationalityNRIC/FINEmailMobile NumberClicking the “I Agree” button permits this digital service to retrieve your data based on the    Terms of Use.CancelI Agree')]</value>
      <webElementGuid>7c024a8d-14ed-4ad9-bfa5-b0efeb31bcbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
