<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_This digital service is requesting the _98b49d</name>
   <tag></tag>
   <elementGuidId>c1aa001f-062a-4d0f-aee7-19d021d72486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.main-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>13962157-b681-4283-881a-8d2114f49234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-logo</value>
      <webElementGuid>379b3737-2a33-4beb-b731-f212ea42b1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test.consent.myinfo.gov.sg/consent-page-template/images/myinfo-com/singpass-logo.png</value>
      <webElementGuid>dc1e03e3-c642-4237-a361-d35c59056918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>40aa7e1b-c266-4986-bf5f-763d36779a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;header-container&quot;]/img[@class=&quot;main-logo&quot;]</value>
      <webElementGuid>ae5d5c5b-fef3-45f5-8680-8e9ff3a04615</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/img</value>
      <webElementGuid>7347d42f-0a3e-4baf-877d-3e888f73c909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>91b9a835-2c4d-4bb9-8a13-eba07d3ab147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5a6a6a87-5425-4081-bd68-8d933d2a7e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://test.consent.myinfo.gov.sg/consent-page-template/images/myinfo-com/singpass-logo.png' and @alt = 'logo']</value>
      <webElementGuid>afef65d7-4bb3-4ac9-8bca-c3dc1e5a7b7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
